README.md, app.json
With this we can create a new Heroku environment with one click.
=> Add Heroku application manifest

config/application.rb, spec/requests/compression_spec.rb
Further reading: http://robots.thoughtbot.com/content-compression-with-rack-deflater
=> Compress responses

app/views/home/show.html.erb, content/6_things_you_need_to_know.md, content/benefits.md, content/complaints.md, content/divorce.md, content/living_abroad.md, content/making_money_last.md, content/pension_pot_options.md, content/pension_pot_value.md, content/pension_types.md, content/scams.md, content/shop_around.md, content/tax.md, content/work_out_income.md
Content updates
* created outstanding articles (except booking appointment)
* updated all articles with latest content and new urls
* updated homepage to link to all articles
=> Latest content with new urls

public/robots.txt
We’ll revert this once we have the correct in-page meta data.
=> Deny robots access to the site

app/views/home/show.html.erb, config/locales/en.yml
Content updates to the homepage
* Update appointment content
* Update title element content to include 'Your money. Your choice.'
=> Homepage updates

app/assets/stylesheets/layout/page/_homepage.scss, app/views/home/show.html.erb, content/shop_around.md
Implement feedback from Alex GC and update 'shop around' content
=> Minor tweaks

spec/requests/caching_spec.rb, spec/requests/favicon_spec.rb, spec/requests/format_spec.rb
spec_helper is already require'd by .rspec
=> DRY up request specs

app/views/components/_journey_nav.html.erb
We already have ``if current_step && current_step == step`` on line 8
=> Don't check twice if `current_step` has been assigned

package.json
This currently broken but we've a [pull request open to fix it](https://github.com/contentful/travis-notify-geckoboard/pull/1).
=> Use our fork of travis-notify-geckoboard

app/views/layouts/_base.html.erb, content/cookies.md
The footer looks a bit sparse at the moment but that will soon change.
I can demo locally if you want to see it rendered.
cc/ @raykhan66 @mcornford
=> Add content about cookies

config/environments/development.rb
=> Disable Rails cache in development

content/pension_pot_options.md
Updated a table heading and an h2 to be consistent with rh nav
=> Make headings consistent with nav

content/scams.md
=> Update Action Fraud telephone number

content/scams.md
Currently displaying as:
Should be displaying as:
=> Add missing line breaks to TPAS contact info

app/assets/javascripts/click-event-logger.js, app/assets/javascripts/click-tracker.js, spec/javascripts/click-event-loggerSpec.js, spec/javascripts/click-trackerSpec.js
Extract the actual event logging from click tracking, and refactor click tracking to allow simpler dependency injection.
The category stuff being in the ClickEventLogger is maybe still a bit weird...
/cc @aduggin
=> Extract ClickEventLogger from ClickTracker

.gitignore, .jscsrc, .jshintrc, .scss-lint.yml, Gemfile, Gemfile.lock, Rakefile, app/assets/javascripts/application.js, app/assets/javascripts/click-event-logger.js, app/assets/javascripts/click-tracker.js, app/views/guides/show.html.erb, config/initializers/jasmine_fixtures.rb, config/routes.rb, content/pension_pot_options.md, lib/tasks/analyse_javascript.rake, package.json, spec/javascripts/click-event-loggerSpec.js, spec/javascripts/click-trackerSpec.js, spec/javascripts/fixtures/gov-uk-template.html, spec/javascripts/fixtures/guide.html, spec/javascripts/fixtures/homepage.html, spec/javascripts/support/jasmine.yml
Uses Universal Analytics to track links in different sections of the page so we can track what parts of the page and which links users are clicking.
Adds jasmine and jquery-jasmine to the project
=> GA click tracking

app/assets/javascripts/click-event-logger.js, spec/javascripts/click-event-loggerSpec.js
Because (for now) we're using GTM!
=> Use GTM to send click tracking events

app/controllers/locations_controller.rb, app/views/locations/index.html.erb, config/routes.rb, features/find_nearest_face-to-face_appointment_locations.feature, features/pages/locations_page.rb, features/step_definitions/appointment_locator_steps.rb, features/support/env.rb, lib/locations.rb, lib/locations/location.rb
First pass at making the _Search using a valid postcode_ scenario pass.
Any opinions on having `Locations` under `lib/` ? Our intention is to keep this aspect of functionality separate from the main Rails app.
As discussed with @gjvis, we want to take an approach of initially faking things at the level of the features, and as we move forward to push the faking "further down the stack" until eventually we have the final implementation paired up with appropriate fixtures.
=> [WIP] Search using valid postcode

app/assets/stylesheets/base/_type.scss, app/assets/stylesheets/components/_highlighted-info.scss, app/assets/stylesheets/lib/_variables.scss, app/assets/stylesheets/pensions-guidance.css.scss, content/appointments.md
Promoting appointments with:
- Highlighted number in big bold blue box
- Bullet points on what one gets
- Shorter info on what to prepare
- Testimonials
_Note:_ flush the cache of [/appointments](https://www.pensionwise.gov.uk/appointments)
=> Revised appointment page.

lib/geocoder.rb, lib/locations.rb, spec/lib/geocoder_spec.rb
There's future work around outcodes to come
=> Put postcode geocoding into it's own thing

.scss-lint.yml
Is this a suitable fix for #211?
=> Configure SCSS-Lint for hyphenated BEM convention

content/cookies.md
=> Add information about performance survey cookies

lib/locations/location.rb, spec/lib/locations/location_spec.rb
This needs more discussion but it's ripped out of #239 and can potentially go straight onto `master`.
=> Derive a slug-like id from Location name

features/find_nearest_face-to-face_appointment_locations.feature, features/step_definitions/appointment_locator_steps.rb
Have discussed the possibility of deleting this scenario with @gjvis but here you go.
=> @wip bookmark search results

app/controllers/locations_controller.rb, app/views/locations/index.html.erb, app/views/locations/show.html.erb, config/routes.rb, features/fixtures/locations.json, features/pages/location_page.rb, features/step_definitions/appointment_locator_steps.rb, features/view_face-to-face_appointment_location_details.feature, lib/locations.rb, spec/controllers/locations_controller_spec.rb
Needs rebased when #238 lands to remove ccae4cc.
Search results:
Links through to:
=> Search results drill down

Gemfile, Gemfile.lock, app/controllers/locations_controller.rb, app/views/locations/invalid_postcode.html.erb, features/find_nearest_face-to-face_appointment_locations.feature, features/pages/locations_page.rb, features/step_definitions/appointment_locator_steps.rb, lib/geocoder.rb, spec/lib/geocoder_spec.rb
Any opinions on the use of exceptions?
=> Search for an invalid postcode

app/decorators/govspeak_guide_decorator.rb
Allows us to put forms into guide content
=> Don't sanitise the Govspeak generated HTML

features/cassettes/Find_nearest_face-to-face_appointment_locations/Bookmark_search_results.yml, features/cassettes/Find_nearest_face-to-face_appointment_locations/Search_using_a_valid_postcode.yml, features/cassettes/View_face-to-face_appointment_location_details/Bookmark_a_appointment_location.yml, features/cassettes/View_face-to-face_appointment_location_details/From_search_results.yml, features/find_nearest_face-to-face_appointment_locations.feature, features/step_definitions/appointment_locator_steps.rb, features/support/vcr.rb, features/view_face-to-face_appointment_location_details.feature
=> VCR cucumber tag

lib/locations/location.rb, lib/locations/repository.rb, spec/fixtures/locations.json, spec/lib/locations/location_spec.rb, spec/lib/locations/repository_spec.rb, spec/lib/locations/search_result_spec.rb, spec/lib/locations/search_spec.rb
Reverts guidance-guarantee-programme/pension_guidance#254
=> Revert "[WIP] Use the GeoJSON Feature ID to identify locations"

app/assets/stylesheets/components/_locations-promo.scss, app/assets/stylesheets/components/_locator-promo.scss, app/views/locations/index.html.erb, app/views/styleguide/components/_locator_promo.html.erb, app/views/styleguide/pages/locations_search.erb
Improve content and layout of locations search and index pages
=> Locations text and layout

app/controllers/locations_controller.rb, app/decorators/location_decorator.rb, app/views/locations/show.html.erb, features/fixtures/locations.json, features/pages/location_page.rb, features/step_definitions/appointment_locator_steps.rb, features/view_face-to-face_appointment_location_details.feature, spec/controllers/locations_controller_spec.rb, spec/decorators/location_decorator_spec.rb
Delivery locations which have a booking location display the opening hours and phone number of the booking location along with the name of the booking location:
=> Delivery location with different booking location

app/views/home/show.html.erb, content/appointments.md
DON'T PUBLISH UNTIL CHANCELLOR SITS DOWN!!!
=> July 2015 budget changes

app.json
To enable Heroku review applications.
=> app.json extra

content/leave_pot_untouched.md, content/pension_pot_options.md
=> 25% tax free info updated and improved

app/validators/email_validator.rb, spec/validators/email_validator_spec.rb
=> Add basic email address validator

app/decorators/search_result_decorator.rb, app/views/locations/index.html.erb, features/fixtures/locations.json, features/pages/locations_page.rb, features/step_definitions/appointment_locator_steps.rb, spec/decorators/search_result_decorator_spec.rb
=> Add address of location to search results

app/assets/stylesheets/components/govspeak/_info-notice.scss, app/views/locations/index.html.erb, app/views/locations/show.html.erb
=> Make it clear you may be able to choose a convenient location

app/views/layouts/locations.html.erb, app/views/locations/show.html.erb, content/appointments.md
This is conveyed later in the journey.
=> Remove information about how to appointment prep

app/views/locations/invalid_postcode.html.erb
=> Make it clear that user has input invalid postcode

app/views/locations/index.html.erb, app/views/locations/show.html.erb
Depends on guidance-guarantee-programme/locator/pull/35
=> Improve explanation of who appointments are with and where

app/controllers/application_controller.rb
Every controller inheriting from it set's it own layout
=> Don't set the layout in `ApplicationController`

app/assets/stylesheets/_govuk-elements.scss, app/controllers/application_controller.rb, app/controllers/concerns/breadcrumbs.rb, app/controllers/guides_controller.rb, app/controllers/locations_controller.rb, app/domain/breadcrumb.rb, app/views/components/_breadcrumbs.html.erb, app/views/locations/index.html.erb, app/views/locations/invalid_postcode.html.erb, app/views/locations/search.html.erb, config/initializers/assets.rb, content/appointments.md, content/book.md, features/guides.feature, features/pages/location_page.rb, features/step_definitions/location_steps.rb, public/robots.txt, spec/controllers/concerns/breadcrumbs_controller_concern_spec.rb, spec/controllers/locations_journey_breadcrumbs_spec.rb, spec/domain/breadcrumb_spec.rb
Two guides allows us to address all the user needs we have.
**TODO:**
=> Break appointment guide into two guides

app/views/components/_locations_search.html.erb, app/views/locations/index.html.erb, app/views/locations/search.html.erb, content/book.md
This is a branch of locations/journey
=> Add search form to booking page and make forms consistent

Gemfile, Gemfile.lock, README.md, app/controllers/locations_controller.rb, app/decorators/location_decorator.rb, app/view_models/location_search_context.rb, app/views/layouts/_base.html.erb, app/views/locations/invalid_postcode.html.erb, app/views/locations/show.html.erb, features/cassettes/View_face-to-face_appointment_location_details/Bookmark_a_appointment_location.yml, features/cassettes/View_face-to-face_appointment_location_details/From_search_results.yml, spec/cassettes/Location_analytics/Search_context_available_to_the_Google_Tag_Manage_dataLayer.yml, spec/controllers/locations_controller_spec.rb, spec/decorators/location_decorator_spec.rb, spec/features/location_analytics_spec.rb, spec/spec_helper.rb, spec/view_models/location_search_context_spec.rb
Surfaces data about locations to the Google Tag Manager dataLayer.
=> Surface information about a location to the dataLayer

content/adjustable_income.md
Legacy wording around taking money flexibly updated
=> Option description change - flexibly to adjustable

content/pension_types.md
Based on discussion with Alistair from TPAS - DB not uncommon for PW audience.
=> Clarification on DB description

app/views/layouts/_base.html.erb, vendor/assets/userzoom.js
Use the updated JS supplied by UserZoom
=> Multiple UserZoom studies

app/views/home/show.html.erb, app/views/layouts/_base.html.erb, vendor/assets/userzoom.js
Think you might like this approach @andrewgarner ;)
=> Disable UserZoom on home page

.jshintrc, .scss-lint.yml, app/assets/javascripts/application.js, app/assets/javascripts/media-player.js, app/assets/javascripts/video.js, app/assets/stylesheets/_govuk-elements.scss, app/assets/stylesheets/_govuk-frontend-toolkit.scss, app/assets/stylesheets/components/_player-container.scss, app/assets/stylesheets/components/_video.scss, app/assets/stylesheets/lib/_variables.scss, app/views/guides/show.html.erb, bower.json, config/initializers/assets.rb, content/take_whole_pot.md, public/captions/take-whole-pot.xml
Adds a video with captions and transcript and progress data published to the GTM data layer
=> Media Player

app/decorators/location_decorator.rb
It can be instatiated three times when rendering a location
=> Memoize the search context

config/application.rb, lib/bounce_browserconfig.rb, spec/lib/bounce_browserconfig_spec.rb
I don't like the `require` in `config/application.rb` but there you go.
=> Bounce browserconfig requests

content/work_out_income.md
See https://www.gov.uk/future-pension-centre
=> Use correct phone number for Future Pension Centre

content/leave_pot_untouched.md
=> guaranteed annuity rate > guaranteed value

content/take_cash_in_chunks.md
guider suggestion - changes to copy also made in summary doc
=> guaranteed annuity rate > guaranteed value 2

content/adjustable_income.md
=> guaranteed annuity rate > guaranteed value 3

content/take_cash_in_chunks.md
New sentence based on TPAS feedback under ## Continuing to pay in
=> Tax relief on paying in

app/assets/javascripts/application.js, app/assets/javascripts/take-whole-pot-calculator.js, app/assets/stylesheets/components/_calculator.scss, app/controllers/take_whole_pot_calculator_controller.rb, app/forms/take_whole_pot_calculator_form.rb, app/helpers/application_helper.rb, app/views/take_whole_pot_calculator/_results.html.erb, app/views/take_whole_pot_calculator/show.html.erb, config/locales/en.yml, config/routes.rb, content/take_whole_pot.md, lib/take_whole_pot_calculator.rb, public/robots.txt, spec/controllers/take_whole_pot_calculator_controller_spec.rb, spec/features/take_whole_pot_calculator_analytics_spec.rb, spec/features/take_whole_pot_calculator_spec.rb, spec/forms/take_whole_pot_calculator_form_spec.rb, spec/helpers/application_helper_spec.rb, spec/lib/take_whole_pot_calculator_spec.rb, spec/spec_helper.rb, spec/support/helpers/with_and_without_javascript.rb
This is a combination of #347 and #356 for deployment. These PRs will be closed.
=> Take whole pot calculator

app/views/take_whole_pot_calculator/show.html.erb, content/take_whole_pot.md
=> Specify that this max amount is for the basic state pension

content/work_out_income.md
=> Citizens Advice name update

content/work_out_income.md
Updates to 'If you have debt' section at bottom
=> Changes to debt content

content/scams.md
Minor wording amend - previously changed to before
=> Scams wording update

content/adjustable_income.md, content/leave_pot_untouched.md, content/take_cash_in_chunks.md, content/take_whole_pot.md
4 pages updated with new content relevant to under 55s
=> Options for under55s

content/tax.md
New section at bottom about pension recycling added as relevant to users under 55
=> New content on pension recycling added

app/views/home/show.html.erb, content/your_pension_before_55.md, features/guides.feature
New guide page on taking pension before 55
=> Over 55 new guide

content/scams.md
New content on bank details scam, deletions of content on financial advisers and GOV.UK homepage and improvements to existing copy eg changing bullets to plain text.
=> Updated scams content

content/work_out_income.md
Edits to 'Costs in retirement' section, new section on 'Paying more into your pot' and more on State Pension deferral and top up.
=> Updated retirement income content for under 55s

content/making_money_last.md
2 hyphens changed to dashes and words 'push back' replaced with 'delay' to improve comprehension of text.
=> Updates to page on making money last

content/pension_pot_value.md
=> Pot value page  - hyphens edit

config/puma.rb
This gives an upstream server a known addressable location.
=> Create puma socket

content/protection.md
New compensation limit is £75k, ref to £85k deleted, hyphens replaced with dashes
=> Edits to how your pension is protected

app/assets/stylesheets/components/_calculator.scss, app/assets/stylesheets/lib/_variables.scss, content/take_whole_pot.md
Apply visually inset style for calculators.
=> Inset calculators

content/making_money_last.md
Line 35 - Changed link for 'care costs' at end of 2nd sentence to link to new care costs page.
=> New_link_making_money_last.md

app/views/home/show.html.erb, content/adjustable_income.md, content/already_bought_annuity.md, content/financial_advice.md, content/living_abroad.md, content/making_money_last.md, content/mix_options.md, content/pension_pot_value.md, content/shop_around.md, content/take_whole_pot.md, content/work_out_income.md, features/guides.feature
cc/ @guidance-guarantee-programme/content-designers @guidance-guarantee-programme/developers
=> Extract financial advice content into new guide

app/views/components/_journey_promo.html.erb, app/views/home/show.html.erb, app/views/styleguide/components.html.erb, app/views/styleguide/components/_journey_nav.html.erb, app/views/styleguide/components/_journey_overview.html.erb, app/views/styleguide/components/_pager.html.erb, app/views/styleguide/pages/homepage.html.erb, app/views/styleguide/pages/journey_index.html.erb, app/views/styleguide/pages/journey_page.html.erb, app/views/styleguide/pages/search_results.erb, content/6_steps_you_need_to_take.html, content/benefits.md, content/making_money_last.md, content/pension_pot_options.md, content/pension_pot_value.md, content/scams.md, content/shop_around.md, content/take_whole_pot.md, content/tax.md, content/work_out_income.md, features/step_definitions/guide_steps.rb
=> Update guides for updated information architecture

content/benefits.md, content/divorce.md, features/step_definitions/guide_steps.rb
Changes to 2 page titles (H1s)
=> H1 changes

content/benefits.md
HMRC was missing so added to relevant sentences.
=> Benefits page update – HMRC added

app/assets/stylesheets/pensions-guidance-print.scss, app/views/layouts/_base.html.erb, config/initializers/assets.rb
Hiding the navigation and search elements for print
=> Adds Pension wise print stylesheet

app/assets/stylesheets/layout/page/_category.scss, app/helpers/application_helper.rb, app/views/categories/show.html.erb
=> Add option circles to category page

content/already_bought_annuity.md
Meta changed from 2016 to 2017.
=> Update meta desc in already bought annuity page

app/assets/javascripts/calculators.js, app/assets/stylesheets/pensions-guidance-print.scss, config/initializers/govspeak.rb, spec/javascripts/calculatorSpec.js
=> Simplify print styles for calculators

features/step_definitions/guide_steps.rb, features/step_definitions/home_page_steps.rb
Uses instance variable that works across pages.
=> Make Cucumber steps more reusable

app/controllers/locations_controller.rb, app/domain/breadcrumb.rb, config/routes.rb, content/appointments.md, content/book_face_to_face.md, content/book_phone.md, features/step_definitions/location_steps.rb, public/robots.txt, spec/controllers/locations_journey_breadcrumbs_spec.rb, spec/domain/breadcrumb_spec.rb
Different pages for booking phone or face to face appointments for Tim's experiment.
Ask Tim if this is ready to go live
:two_men_holding_hands:
=> Phone vs face to face appointments

app/controllers/calculators/leave_pot_untouched_controller.rb, app/forms/calculators/leave_pot_untouched_form.rb, app/helpers/application_helper.rb, app/views/calculators/_form_input_currency.html.erb, app/views/calculators/_form_input_submit.html.erb, app/views/calculators/leave_pot_untouched/_calculator.html.erb, app/views/calculators/leave_pot_untouched/_form.html.erb, app/views/calculators/leave_pot_untouched/_result.html.erb, app/views/calculators/leave_pot_untouched/show.html.erb, config/locales/en.yml, config/routes.rb, content/leave_pot_untouched.md, features/calculators.feature, features/pages/leave_pot_untouched_guide_page.rb, features/step_definitions/calculator_steps.rb, features/support/poltergeist.rb, features/support/vcr.rb, lib/financial.rb, lib/leave_pot_untouched_calculator.rb, public/robots.txt, spec/features/leave_pot_untouched_analytics_spec.rb, spec/forms/calculators/leave_pot_untouched_form_spec.rb, spec/lib/financial_spec.rb, spec/lib/leave_pot_untouched_calculator_spec.rb, spec/routing/calculators_spec.rb
Adds calculator to estimate how pot growth if left untouched for 5 years. Estimation assumes an interest rate of 3% and interest compounded monthly.
=> Leave pot untouched calculator

app/views/calculators/leave_pot_untouched/_form.html.erb, app/views/calculators/take_whole_pot/_result.html.erb, spec/features/leave_pot_untouched_analytics_spec.rb, spec/features/take_whole_pot_calculator_analytics_spec.rb
The GTM tag will use a trigger that listens for this event.
=> Add GTM custom event `CalculatorEstimate`

app/helpers/application_helper.rb, app/repositories/category_repository.rb, app/repositories/guide_repository.rb, app/views/calculators/leave_pot_untouched/_form.html.erb, app/views/calculators/take_whole_pot/_form.html.erb
https://bugs.ruby-lang.org/issues/11537
=> Use Ruby 2.3’s safe navigation operator

content/take_cash_in_chunks.md
Added dash to example to make it easier to read.
=> Change to cash in chunks page

content/making_money_last.md
Made changes as part of ongoing website improvements to make worst performing pages easier to read and understand.
=> Improved make your money last guide

content/work_out_income.md
Changes made to make the page more concise and easier to read. Part of a review of 3 pages.
=> Improved work out income guide

app/assets/stylesheets/components/_nav.scss, app/helpers/navigation_helper.rb, app/view_models/navigation.rb, spec/view_models/navigation_spec.rb
Adds 'What you can do with your pot' overview link.
=> Add subcategory `parent` links to navigation

content/contact.md
=> Edits to contact us page

content/take_cash_in_chunks.md, content/take_whole_pot.md
A few tweaks to the options pages
=> Option pages tweaks

content/tax.md
Tax page reworked as part of ongoing website improvements
=> Redrafted tax page

content/tax.md
Further updates made for testing tomorrow
=> More updates to tax page

content/book_phone.md
Is this OK to go live @mattlucht ? 
:cactus:
=> New phone number

content/guaranteed_income.md
Added scams header to make it consistent across the site.
=> Scams header

content/adjustable_income.md
Added to keep scam content consistent across the options
=> Added Scams H2 and text

content/shop_around.md
Made changes as part of ongoing improvement of worst performing pages.
=> Improve_shop_around_page

content/guaranteed_income.md
Merged 2 next step bullets as they were doing the same thing - came out of looking at the bullets again as part of lab testing.
=> Edit next step bullets

content/guaranteed_income.md
Added full stop - my bad it wasn't in there when I updated the bullet.
=> added full stop

content/tax.md
Added missing hyphens, edited page overview to make clearer.
=> Update tax page

content/contact.md
Updated contact for DWP complaints relevant from April 1st changeover - today!
=> Updated to DWP

app/assets/stylesheets/layout/_common_page_structure.scss, app/views/layouts/_base.html.erb
=> Add link to GOV.UK accessibility statement

content/ill_health.md, content/state_pension.md, content/take_cash_in_chunks.md, content/tax.md, content/when_you_die.md
Here are the files to go live tomorrow. Please eat breakfast before merging.
=> 6 april changes

content/pension_types.md
April 6 changes and improvements to the page all in one bundle. To go live 6 April.
=> Improve pension types

content/work_out_income.md
April 6 changes to State Pension amount and Personal Allowance. Figures updated in 60s and 70s sections.
=> Update changes to 'Work out income' page

app/views/layouts/_base.html.erb
This will replace the current website survey.
**To be deployed on Thursday April 7**
=> Point survey intercept tool to flexible appointment survey

app/assets/javascripts/calculators.js, app/controllers/calculators/guaranteed_income_controller.rb, app/forms/calculators/guaranteed_income_form.rb, app/views/calculators/_error_summary.html.erb, app/views/calculators/_form_input_number.html.erb, app/views/calculators/guaranteed_income/_calculator.html.erb, app/views/calculators/guaranteed_income/_estimate.html.erb, app/views/calculators/guaranteed_income/_form.html.erb, app/views/calculators/guaranteed_income/show.html.erb, config/locales/en.yml, config/routes.rb, content/guaranteed_income.md, features/calculators.feature, features/pages/guaranteed_income_page.rb, features/step_definitions/calculator_steps.rb, lib/guaranteed_income_calculator.rb, spec/features/guaranteed_income_analytics_spec.rb, spec/forms/calculators/guaranteed_income_form_spec.rb, spec/javascripts/calculatorSpec.js, spec/routing/calculators_spec.rb
=> Guaranteed income calculator

app/views/calculators/take_cash_in_chunks/_form.html.erb
This tested well in our user research sessions
=> Update take cash in chunks calculator copy

Gemfile, Gemfile.lock
As we write more complex components, bringing this in will simplify the SCSS we need to write.
https://github.com/postcss/autoprefixer
=> Add `autoprefixer-rails`

app/assets/javascripts/calculators.js, app/assets/javascripts/components/Slider.es6, app/assets/stylesheets/helpers/_highlight.scss, app/assets/stylesheets/lib/_variables.scss, app/controllers/calculators/adjustable_income_controller.rb, app/forms/calculators/adjustable_income_form.rb, app/views/calculators/_form_input_hidden.html.erb, app/views/calculators/adjustable_income/_calculator.html.erb, app/views/calculators/adjustable_income/_estimate.html.erb, app/views/calculators/adjustable_income/_form.html.erb, app/views/calculators/adjustable_income/show.html.erb, app/views/components/_slider.html.erb, config/locales/en.yml, config/routes.rb, content/adjustable_income.md, features/calculators.feature, features/pages/adjustable_income_guide_page.rb, features/step_definitions/calculator_steps.rb, lib/adjustable_income_calculator.rb, spec/forms/calculators/adjustable_income_form_spec.rb, spec/javascripts/fixtures/slider.html, spec/javascripts/sliderSpec.js, spec/routing/calculators_spec.rb
=> Adjustable income calculator

.travis.yml
This isn't being observed plus it isn't actually configured correctly.
=> Remove geckoboard build reporting

app/views/home/show.html.erb
Section under 'Talk about your pension options' changed to reduce duplication. Also added 'printed' so that user knows summary won't just be verbal.
=> Update homepage text

content/your_pension_before_55.md
=> Update Taking pension before 55 page

app/views/layouts/_base.html.erb
This will likely be removed when Aman's free trial runs out.
=> Adds the crazy egg tracker temporarily

content/already_bought_annuity.md
Line removed due to policy change making it factually inaccurate.
=> Update 'If you've already bought an annuity page'

content/adjustable_income.md, content/take_cash_in_chunks.md
Done as part of ongoing web improvement
=> Reposition calc

content/guaranteed_income.md
Calc repositioned on page as part of ongoing web improvements
=> Reposition calc 1

content/when_you_die.md
Whole page review. Multiple changes to reduce duplication of 'money still in your pot' content and increase general comprehension of subject.
=> Update 'Your pension when you die' guide

app/views/calculators/take_cash_in_chunks/_estimate.html.erb
Users can adjust the amount of their first chunk using a slider
=> Slider on take cash in chunks calculator

app/views/calculators/leave_pot_untouched/_calculator.html.erb, app/views/calculators/leave_pot_untouched/_estimate.html.erb
Users can adjust their monthly contribution using the slider
to see the affect on their pot size over time.
=> Slider on leave your pot untouched calculator

app/domain/taxonomy.rb, content/can_i_sell_my_annuity.md
=> Introduce 'can I sell my annuity' content

app/assets/javascripts/slot-picker.es6.erb, app/assets/stylesheets/pensions-guidance.scss, app/assets/stylesheets/vendor/_slot-picker.scss, app/controllers/booking_requests_controller.rb, app/views/booking_requests/new.html.erb, bower.json, config/initializers/assets.rb
Built upon the [Ministry of Justice Slot Picker](https://github.com/ministryofjustice/moj_slotpicker).
Needs wiring up to the backend etc.
=> Booking request slot picker

app/views/layouts/_base.html.erb
This was requested by Homam for an Annuities experiment.
=> Update user zoom intercept script identifiers

content/protection.md
Rewritten to improve readability score of page.
=> Improve protection page

config/initializers/online_booking_locations.rb
Enable online booking for Hackney and its associated locations in the
staging environment.
=> Configure staging online booking locations

content/scams.md
Link to PDF of example scams updated after request from The Pensions Regulator. PDF now 5 pages.
=> Update pension scams page

app/views/booking_requests/step_one.html.erb, app/views/booking_requests/step_two.html.erb
Can be used to monitor how many users are seeing errors with
their input, and on which step the input error occurred.
=> GTM tracking events for form validation errors

Gemfile, Gemfile.lock, app/assets/javascripts/application.js, app/assets/javascripts/feedback.js, app/assets/stylesheets/components/_feedback.scss, app/controllers/booking_requests_controller.rb, app/controllers/feedback_controller.rb, app/forms/booking_feedback_form.rb, app/views/booking_requests/ineligible.html.erb, app/views/booking_requests/step_one.html.erb, app/views/booking_requests/step_two.html.erb, app/views/feedback/_feedback_form.html.erb, app/views/feedback/_form.html.erb, app/views/feedback/_result.html.erb, app/views/feedback/feedback.html.erb, config/routes.rb
Progressively enhanced to keep the user in the same place they
were when javascript is available.
Creates a Zendesk ticket in the format:
```
Name: Customer name
Email: Customer email
Message: Customer comments
```
=> Online Booking feedback form

content/protection.md
=> Update pension protection guide

app/assets/stylesheets/vendor/_slot-picker.scss, app/views/booking_requests/completed.html.erb, app/views/booking_requests/ineligible.html.erb, app/views/booking_requests/step_one.html.erb, app/views/booking_requests/step_two.html.erb
Moves 'Change Dates' link to below the dates on step two.
=> Online booking forms content tweaks

config/initializers/online_booking_locations.rb
Enables Hackney and its associated booking centres for online bookings.
=> Enable Hackney and its associated locations

app/controllers/feedback_controller.rb
So the feedback can easily be identified in Zendesk.
=> Tag tickets created from feedback form with `online_booking`

app/controllers/feedbacks_controller.rb, app/forms/booking_feedback_form.rb, app/views/booking_requests/ineligible.html.erb, app/views/booking_requests/step_one.html.erb, app/views/booking_requests/step_two.html.erb, app/views/feedback/feedback.html.erb, app/views/feedbacks/_feedback_form.html.erb, app/views/feedbacks/_form.html.erb, app/views/feedbacks/_result.html.erb, app/views/feedbacks/new.html.erb, app/views/feedbacks/thanks.html.erb, config/initializers/feedback.rb, config/routes.rb, features/customer_booking_request.feature, features/customer_leaves_feedback.feature, features/pages/booking_step_one.rb, features/pages/feedback_page.rb, features/sections/feedback.rb, features/step_definitions/customer_booking_request_steps.rb, features/step_definitions/feedback_steps.rb, lib/feedback.rb, lib/feedback/stub_client.rb, lib/feedback/zen_desk_client.rb, spec/lib/feedback/zen_desk_client_spec.rb
* Rework controller actions to follow 'RESTful' structure
* Make Zendesk client pluggable / stubable
* Adds features to specify feedback behaviour
=> Rework feedback for testability

app/views/calculators/take_cash_in_chunks/_form.html.erb, app/views/calculators/take_whole_pot/_form.html.erb
=> Calculator copy changes

app/controllers/calculators/annuity_controller.rb, app/forms/calculators/annuity_form.rb, app/views/calculators/_form_input_currency.html.erb, app/views/calculators/annuity/_calculator.html.erb, app/views/calculators/annuity/_estimate.html.erb, app/views/calculators/annuity/_form.html.erb, app/views/calculators/annuity/show.html.erb, config/locales/en.yml, config/routes.rb, content/how_to_sell_an_annuity.md, lib/annuity_calculator.rb, lib/income_tax_calculator.rb
Prototype implementation for testing
=> Annuities calculator

.gitignore, Gemfile, Gemfile.lock, README.md, package.json, wraith/configs/capture.yaml
* run wraith: 'npm run wraith'
=> Adding wraith to test pensionwise pages across device widths

app/views/layouts/_base.html.erb, content/customer_promise.md
Linked to from the support links in the footer.
=> Customer promise

wraith/configs/capture.yaml
This page is a first class citizen as it is in front of customers,
so this will have wraith compare visual changes to it as well.
This was plucked from #611.
=> Adds homepage experiment to wraith config

config/initializers/online_booking_locations.rb
Enables Barry and its associated booking locations for online bookings.
=> Enable Barry / Cardiff and Vale online bookings

config/initializers/online_booking_locations.rb
Adds the remaining associated booking locations and removes one errant
location.
=> Add remaining booking locations for Barry

app/controllers/feedbacks_controller.rb, app/forms/booking_feedback_form.rb, config/initializers/feedback.rb, config/initializers/zen_desk.rb, lib/zen_desk.rb, lib/zen_desk/client.rb, lib/zen_desk/stub_client.rb, spec/lib/zen_desk/client_spec.rb
This is to support reuse of the code for annuities registration.
=> Refactor zendesk interface

app/views/booking_requests/step_two.html.erb
Adds a missing `</div>` at the end and fixes allignment
=> Add missing close div tag

app/controllers/annuity_registration_controller.rb, app/forms/annuity_registration_form.rb, app/views/annuity_registration/new.html.erb, app/views/annuity_registration/success.html.erb, config/locales/en.yml, config/routes.rb, content/already_bought_annuity.md, lib/zen_desk/client.rb, spec/features/annuity_registration_spec.rb
Send registration details to ZenDesk for data storage
=> [DO NOT MERGE] Register for annuities

content/already_bought_annuity.md
Changes to register interest copy and general tidying up.
=> Update 'If you've already bought an annuity' page

app/domain/taxonomy.rb, content/benefits.md, content/can_sell_annuity.md, content/care_costs.md, content/financial_advice.md, content/guaranteed_income.md, content/how_to_sell_annuity.md
Incs:
New 'How to sell...' page
New 'Check if you can sell...' page
Additions to care costs, benefits, guaranteed income and financial advice pages.
=> New annuity content

config/initializers/online_booking_locations.rb
Enable Taunton and its associated locations.
=> Enable Taunton for online bookings

lib/tasks/analyse_javascript.rake
Returns the correct exit code, rather than raising an exception.
=> Exit with correct exit code

content/pension_statements.md, content/transfer_pension.md
=> Transfer pension content

app/views/styleguide/pages/appointments.erb, content/appointments.md, content/financial_advice.md
content change to reflect changes to the summary document process and
fixed a broken link on the ‘Seeing a financial adviser’ page
=> Content changes

content/how_to_sell_annuity.md
'Types of annuity' link changed as was incorrect.
=> Update 'How to sell an annuity' page

app/assets/stylesheets/vendor/_slot-picker.scss, app/views/booking_requests/step_one.html.erb
See individual commits for more context.
=> Slot picker tweaks from user research findings

app/views/home/experiment.html.erb
from https://www.gov.uk/performance/pension-wise
=> Updating home experiment stats figures

content/your_pension_before_55.md
Change debt sentence in response to feedback
=> Change debt sentence

content/can_sell_annuity.md, content/selling_your_annuity.md
Made a few little changes after feedback.
=> Annuity content change

content/transfer_pension.md
=> Update Pension transfers page

content/tesco.md
=> Tesco pilot booking page

app/controllers/booking_requests_controller.rb, app/views/booking_requests/completed.html.erb, app/views/booking_requests/ineligible.html.erb, app/views/booking_requests/step_one.html.erb, app/views/booking_requests/step_two.html.erb
Analytics would like to see the booking centre and delivery centre
surfaced in the data layer so we can effectively track marketing
campaigns.
=> Surface booking location information in the data layer

app/views/home/show.html.erb
As we do not only print and send summary documents the content has been
changed to reflect this
=> Change to content to reflect summary document process change

app/domain/breadcrumb.rb, app/views/booking_requests/ineligible.html.erb, app/views/booking_requests/step_two.html.erb, app/views/locations/index.html.erb, app/views/styleguide/pages/locations_index.erb, content/book_face_to_face.md, features/step_definitions/location_steps.rb
Changes to content throughout the booking journey.
=> Content changes to the booking journey

config/initializers/online_booking_locations.rb
Enable online bookings for Wycombe and its associated delivery centres.
=> Enable Wycombe for online bookings

config/initializers/online_booking_locations.rb
Enables online bookings for these locations.
We need to start thinking about ways to automate this process given the rate of
new locations we'll be bringing online.
=> Enable Bournemouth and associated locations

lib/guaranteed_income_calculator.rb, spec/features/guaranteed_income_analytics_spec.rb
Rates updated based on:
https://pensions-guidance.atlassian.net/wiki/display/WIKI/averaged+annuity+rate
=> Update annuity rates for guaranteed income calculator

app/controllers/application_controller.rb, app/views/layouts/_base.html.erb, app/views/research/_user_zoom.html.erb
Extract UserZoom JS to it's own file and
set ID, SID and customer ID from ENV variables instead 
of hard-coding into the page.
=> Refactor UserZoom JS include

app/controllers/home_controller.rb, app/views/home/experiment.html.erb, app/views/research/_google_experiments.html.erb, config/routes.rb
Add 'Book appointment link' experiment
Remove 'home-intro__link' class from book
appointment link so that it uses standard 
link colouring instead of being grey text.
Extract 'google experiments' JS to its own partial.
=> Book appointment link a/b test

config/initializers/online_booking_locations.rb
Enables Wolverhampton and its child locations for online bookings.
=> Enable Wolverhampton for online bookings

app/views/home/experiment.html.erb, app/views/home/show.html.erb
Per the [performance platform](https://www.gov.uk/performance/pension-wise)
=> Update statistics on homepage

content/after_your_appointment.md
Adding a exit poll survey link for users that have had a phone
appointment.
=> Exit poll survey link

app/views/booking_requests/step_one.html.erb, app/views/booking_requests/step_two.html.erb, config/locales/en.yml
Online booking journey content improvement
=> Online booking journey content improvement

app/views/home/show.html.erb
Content changes to better reflect the surfacing of the postcode search
on the homepage
=> Content changes on homepage

config/initializers/online_booking_locations.rb
Switches online bookings on for these locations.
=> Enable Morden and its child locations

app/views/home/experiment.html.erb
This will allow the "Book an appointment" link colour
experiment to be started.
=> Update homepage experiment to use the latest assets

app/views/locations/index.html.erb, app/views/locations/show.html.erb
Amend content to better reflect booking hours
=> Amend content to better reflect booking hours

content/transfer_pension.md
Replaced ## Calculate if it’s worth moving section with sections on checking which pension options the new provider offers and info on fees.
=> Update pension transfer page

app/assets/stylesheets/components/_form.scss, app/views/booking_requests/completed.html.erb, app/views/booking_requests/step_one.html.erb, app/views/booking_requests/step_two.html.erb
Content changes based on the latest lab session outcomes.
=> Content changes to the online booking journey

app/assets/stylesheets/components/_form.scss, app/views/booking_requests/step_two.html.erb, app/views/home/experiment.html.erb, app/views/home/show.html.erb, content/appointments.md
Improve content to "sell" appointments to customers
=> Improve content to "sell" appointments to customers

app/views/booking_requests/step_one.html.erb
Highlight lack of appointment availability on slot picket page
=> Highlight lack of appointment availability

app/views/booking_requests/completed.html.erb, app/views/booking_requests/step_two.html.erb
Content to reinforce select appointments may not be available and
consistency around e.g. on the customer details page
=> Content to reinforce select appointments may not be available

features/step_definitions/calculator_steps.rb, lib/guaranteed_income_calculator.rb, spec/features/guaranteed_income_analytics_spec.rb
Update annuity rates with latest data
=> Update Annuity calculator constants - Nov 2016

app/assets/javascripts/application.js, app/assets/javascripts/disable-button.js
=> Ensure button is disabled after submission

content/privacy.md
Latest changes to privacy policy based on the DPA work
=> Latest changes to privacy policy

app/assets/stylesheets/components/govspeak/_info-notice.scss, app/views/components/_locations_search.html.erb, app/views/locations/failed_lookup.html.erb, app/views/locations/invalid_postcode.html.erb, app/views/locations/search.html.erb, content/appointments.md, content/book_face_to_face.md
Update the headers and content around the booking journey.
Ensure the look and feel of the booking journey search forms is consistent, reusing the existing search partial where possible.
=> Booking content improvements

app/views/home/show.html.erb
The phone number is currently not working so this is a first fix.
=> Temporarily remove phone number as services are down

app/views/appointment_summaries/create.html.erb, app/views/appointment_summaries/new.html.erb, app/views/booking_requests/step_one.html.erb, app/views/booking_requests/step_two.html.erb, app/views/feedbacks/new.html.erb, app/views/feedbacks/thanks.html.erb, app/views/home/show.html.erb, app/views/locations/failed_lookup.html.erb, app/views/locations/index.html.erb, app/views/locations/invalid_postcode.html.erb, app/views/locations/search.html.erb, app/views/locations/show.html.erb, content/state_pension.md
=> Website amends

app/domain/output_document.rb, app/views/appointment_summaries/new.html.erb, config/initializers/supplementary_options.rb, features/pages/appointment_summary_generator.rb, features/step_definitions/appointment_summary_steps.rb
Add a checkbox to allow this section to be rendered
on the summary document.
=> [DO NOT MERGE] 'Transfer of Pension Pot' supplementary section

app/assets/stylesheets/helpers/_two-column-list.scss, app/controllers/questions_controller.rb, app/domain/taxonomy.rb, app/repositories/guide_repository.rb, app/views/home/show.html.erb, app/views/questions/_pension_start_year_question.html.erb, app/views/questions/_yes_no_dont_know_question.html.erb, config/initializers/govspeak.rb, config/routes.rb, content/appointments.md, content/pension_type_tool.md, content/pension_type_tool/defined_contribution.md, content/pension_type_tool/might_defined_contribution.md, content/pension_type_tool/most_cases_defined_benefit.md, content/pension_type_tool/most_cases_defined_contribution.md, content/pension_type_tool/question_1.md, content/pension_type_tool/question_2.md, content/pension_type_tool/question_3.md, content/pension_type_tool/question_4.md, content/pension_types.md, spec/features/govspeak_questions_spec.rb, spec/fixtures/nested/nested_guide.md, spec/fixtures/yes_no_dont_know_question.md, spec/repositories/guide_repository_spec.rb
Add new rendering options for govspeak questions.
This can be incorporated into the existing markdown
to add questions to a page.
=> Pension types questions

app.json
These are required for preview deploys.
=> Restore missing buildpacks

app/assets/javascripts/video-player.js.es6
- Feedback from the analytics team suggested we needed to
push slightly different values
=> Alter dataLayer push values for player state change

app/assets/javascripts/video-player.js.es6
- feedback from Analytics team was that we need an event name
=> Adding event for player state change

content/pension_type_tool.md
Added another 'free' for the benefit of users coming directly to the tool from paid search.
=> Added free

app/assets/javascripts/disable-button.js
- old code was updating the button of both form buttons
rather than just the button clicked
=> Fix bug with disabling buttons when there is two forms

app/models/telephone_appointment.rb, config/locales/en.yml, spec/models/telephone_appointment_spec.rb
There was no validation being performed on this form value prior to
this change.
=> Ensure a DC eligibility option is chosen

app/models/telephone_appointment.rb, spec/models/telephone_appointment_spec.rb
We allow anyone 50 and over to attend an appointment.
=> Correctly verify age eligibility for appointments

app/assets/stylesheets/components/slot-picker/_slot-picker-header.scss, app/views/telephone_appointments/_step_3.html.erb
=> Add in help text on phone appointment booking form

app/lib/guaranteed_income_calculator.rb
Update annuity rates with latest data
=> Update Annuity calculator constants - Feb 2017

content/pension_statements.md
=> Mend H2 markdown

Gemfile.lock
Ensure the cache is evicted with respect to the configured TTL.
=> Bump `booking_locations` for cache expiry

app/views/appointment_summaries/new.html.erb
Odd wording updated to make consistent with above check box options.
=> Update 'How to view your appointment summary'

app/views/application/_ineligible.html.erb, app/views/booking_requests/ineligible.html.erb, app/views/telephone_appointments/confirmation.html.erb, app/views/telephone_appointments/ineligible.html.erb
We are using separate surveys to track feedback for both channels.
=> Differentiate F2F and telephone booking feedback

app/lib/guaranteed_income_calculator.rb, features/step_definitions/calculator_steps.rb
Update annuity rates with latest data
=> Update Annuity calculator constants - Mar 2017

config/initializers/filter_parameter_logging.rb
We should filter this sensitive information from logs.
=> Filter sensitive booking parameters from logs

content/pension_type_tool/defined_contribution.md, content/pension_type_tool/might_defined_contribution.md, content/pension_type_tool/most_cases_defined_benefit.md, content/pension_type_tool/most_cases_defined_contribution.md
=> Add in survey feedback link for pension type tool

app/views/telephone_appointments/_step_3.html.erb
Clarifies this copy to better describe what it means and how we will
potentially contact the customer.
=> Clarify optout label and hint

app/views/calculators/adjustable_income/_estimate.html.erb, app/views/calculators/guaranteed_income/_estimate.html.erb, app/views/calculators/take_cash_in_chunks/_estimate.html.erb, app/views/calculators/take_whole_pot/_estimate.html.erb, content/adjustable_income.md, content/financial_advice.md, content/pension_types.md, content/state_pension.md, content/take_cash_in_chunks.md, content/tax.md, content/work_out_income.md
Update copy on site for new tax year
=> New tax year copy changes

app/views/booking_requests/step_two.html.erb, app/views/telephone_appointments/_step_3.html.erb
=> Wording changes

app/forms/booking_request_form.rb, app/models/telephone_appointment.rb, app/views/booking_requests/step_two.html.erb, app/views/telephone_appointments/_step_3.html.erb, app/views/telephone_appointments/new.html.erb, config/locales/en.yml
DWP feedback suggested improved content for error messages.
=> Add better error messages for both booking journeys

app/lib/guaranteed_income_calculator.rb, spec/features/guaranteed_income_analytics_spec.rb
Updates the rates used for calculations.
=> Update latest averaged annuities rate

config/locales/en.yml
Without these the advice is harshly worded.
=> Provide friendly validation messages

app/assets/stylesheets/components/_marketing.scss, app/controllers/marketing_controller.rb, config/routes.rb
=> Create /about endpoint and fix styling of marketing page

content/state_pension.en.md, content/work_out_income.en.md
Changed lines around SP top up to bring them up to date.
=> Update SP rules

app/lib/guaranteed_income_calculator.rb
Updated the average annuities rates that are used by the ‘Get a
guarantee income’ calculator.
=> Update averaged annuities ratess

app/assets/stylesheets/components/_notice.scss, app/controllers/booking_requests_controller.rb, app/forms/booking_request_form.rb, app/lib/locations.rb, app/lib/locations/location.rb, app/lib/locations/search.rb, app/views/booking_requests/step_one.html.erb, app/views/locations/index.html.erb, app/views/locations/show.html.erb, spec/cassettes/Alternative_locations/when_there_are_less_than_three_slots_available/and_nearby_alternatives.yml, spec/cassettes/Alternative_locations/when_there_are_less_than_three_slots_available/but_no_nearby_alternatives.yml, spec/features/alternative_locations_spec.rb, spec/fixtures/locations_with_alternates.json, spec/lib/locations/search_spec.rb
**Limited availability warning on search results**
**Alternate location suggestions on booking page**
Locations within 5 miles with 3 or more available slots.
Left the two refactoring commits separate for review, will rebase in before merging.
=> Limited availability

public/robots.txt
=> Add styleguide to robots.txt

config/locales/cy.yml, config/locales/en.yml
This link was duplicated accidentally.
=> Fix issues with quick links after introduction of welsh homepage

app/assets/javascripts/click-tracker.js, app/views/pension_summaries/summary.html.erb
By tracking clicks on the print and download buttons.
=> Track printing and downloading of pension summaries

app/controllers/application_controller.rb, app/controllers/guides_controller.rb, app/controllers/pension_summaries_controller.rb
Took a step back and realised this was a much better approach.
=> Refactor implementation of `alternate_url`

content/selling_your_annuity.cy.md, content/selling_your_annuity.en.md
Got rid of some content that was brought to our attention by providers
=> Removed incorrect content

content/after_your_appointment.cy.md, content/after_your_appointment.en.md
Remove survey link - no longer needed.
=> Remove survey link

content/pension_summary/taking_my_pension_if_im_ill.cy.md, content/pension_summary/taking_my_pension_if_im_ill.en.md
=> Self serve journey copy change

content/ill_health.cy.md, content/ill_health.en.md
Tax rules have changed - updated for accuracy
=> Update tax rule

content/after_your_appointment.cy.md, content/after_your_appointment.en.md
This is content to address the same matter that was recently customised on the cover letter, about section 32/adjustable income/inherited pot situations.
Needs a translation to be requested from @arwelowen.
=> Add info to the intro before "after your appointment"

config/locales/cy.yml, config/locales/en.yml
Will need a translation from @arwelowen before being merged.
=> Add words “defined contribution” to the home page content

content/for_employers.cy.md
Seems this is a side effect of taking a Windows WordPad rtf as source.
=> Fix mangled Welsh character

app/controllers/pension_summaries_controller.rb, config/locales/pension_summaries.cy.yml, config/locales/pension_summaries.en.yml, content/pension_summary/final.cy.md, content/pension_summary/get_a_guaranteed_income.cy.md, content/pension_summary/get_an_adjustable_income.cy.md, content/pension_summary/getting_help_with_debt.cy.md, content/pension_summary/how_my_pension_affects_my_benefits.cy.md, content/pension_summary/how_my_pension_is_taxed.cy.md, content/pension_summary/leave_your_pot_untouched.cy.md, content/pension_summary/mix_your_options.cy.md, content/pension_summary/print_introduction.cy.md, content/pension_summary/scams.cy.md, content/pension_summary/start.cy.md, content/pension_summary/step_one.cy.md, content/pension_summary/step_two.cy.md, content/pension_summary/take_cash.cy.md, content/pension_summary/take_whole.cy.md, content/pension_summary/taking_my_pension_if_im_ill.cy.md, content/pension_summary/transferring_my_pension_to_another_provider.cy.md
As provided by our man in Pwllheli, Arwel.
=> Add welsh translations to the self serve journey

content/adjustable_income.en.md, content/pension_summary/get_an_adjustable_income.cy.md, content/pension_summary/get_an_adjustable_income.en.md, content/pension_summary/take_cash.cy.md, content/pension_summary/take_cash.en.md, content/pension_summary/take_whole.cy.md, content/pension_summary/take_whole.en.md, content/take_cash_in_chunks.en.md, content/take_whole_pot.en.md
Link to MPAA specific guidance given by GOV.UK.
=> Link to GOV.UK guidance

Gemfile, Gemfile.lock
Includes recent covering letter modifications.
=> Bump `output-templates`

app/controllers/guides_controller.rb, content/appointments.cy.md, public/robots.txt, spec/features/locales_spec.rb
As Pension Wise will be delivering appointments in welsh, content  changes have been made to reflect the booking process.
=> Content update based on welsh appointment

app/controllers/guides_controller.rb, content/appointments.cy.md, public/robots.txt, spec/features/locales_spec.rb
Reverts guidance-guarantee-programme/pension_guidance#988
This can't go out yet.
=> Revert "Content update based on welsh appointment"

app/controllers/guides_controller.rb, content/appointments.cy.md, public/robots.txt, spec/features/locales_spec.rb
Reverts guidance-guarantee-programme/pension_guidance#990
This can wait here until launch now.
=> Reintroduce Welsh booking changes

app/controllers/booking_requests_controller.rb, app/forms/booking_request_form.rb, app/lib/booking_requests/api_mapper.rb, app/lib/placed_by_agent.rb, spec/forms/booking_request_form_spec.rb, spec/lib/booking_requests/api_mapper_spec.rb
This identifies bookings based on the agent's remote IP address.
=> Identify bookings placed by a TP agent

app/controllers/guides_controller.rb, content/appointments.cy.md, public/robots.txt, spec/features/locales_spec.rb
Reverts guidance-guarantee-programme/pension_guidance#991
This has been reverted again due to issues with the IVR.
=> Revert "Reintroduce Welsh booking changes"

app/lib/tesco/location.rb, app/views/tesco/locations/index.html.erb, spec/features/tesco_locations_spec.rb
Shows the location is fully booked when it has no availability.
=> Disable bookings for fully booked locations

app/views/tesco/locations/index.html.erb
Previously this message was slightly jarring.
=> Display 'fully booked' message when no locations

app/controllers/locations_controller.rb, app/forms/booking_request_form.rb, app/helpers/locations_helper.rb, app/lib/booking_requests/api_mapper.rb, app/lib/placed_by_agent.rb, app/views/locations/index.html.erb, app/views/locations/show.html.erb, features/pages/location_page.rb, spec/features/agent_bookings_spec.rb, spec/forms/booking_request_form_spec.rb, spec/lib/booking_requests/api_mapper_spec.rb
Identifies TP agents and gives them a custom path when placing bookings on behalf of a customer.
=> Identify agents for customer bookings

content/your_pension_before_55.cy.md, content/your_pension_before_55.en.md
Removes now defunct debt guidance content.
=> Remove defunct debt guidance

.travis.yml
=> Explicitly install bundler

Gemfile, Gemfile.lock, content/pension_summary/final.en.md, content/pension_summary/get_a_guaranteed_income.en.md, content/pension_summary/taking_my_pension_if_im_ill.en.md
Alters this content inline with the latest `output-templates`.
=> Summary content changes

app/lib/where_you_heard.rb
=> Add additional WDYH option

app/views/layouts/home.html.erb
For marketing and research purposes.
=> Add console verification tag

app/views/booking_requests/completed.html.erb
Mention that emails may be directed to the customer's spam folder and
that they should check there in the first instance.
=> Spam warning

content/book_face_to_face.cy.md, content/book_face_to_face.en.md, content/living_abroad.cy.md, content/living_abroad.en.md
This is due to the recent adverse weather.
Also fixes a broken link.
=> Draw attention to the potential delays

Gemfile.lock, content/pension_summary/final.cy.md, content/pension_summary/final.en.md
=> Replace MAS number with the latest

app/controllers/tesco/locations_controller.rb, app/lib/tesco/location.rb, app/views/tesco/locations/index.html.erb, app/views/tesco/locations/show.html.erb, config/routes.rb, features/pages/tesco_location.rb, features/pages/tesco_locations.rb, spec/features/tesco_locations_spec.rb
Lists the locations in a first letter style index page. Clicking through
brings the customer to the details for that particular location.
=> List Tesco locations in a simple grouped index

content/book_face_to_face.cy.md, content/book_face_to_face.en.md
This reverts commit f0d0b6c6fac20a227fd8b491e2113deb56e6b82a.
Removes the weather warning since it no longer applies.
=> Revert "Draw attention to the potential delays"

config/locales/calculators/adjustable_income.en.yml, config/locales/calculators/guaranteed_income.en.yml, config/locales/calculators/take_cash_in_chunks.en.yml, config/locales/calculators/take_whole_pot.en.yml
Makes changes as requested by David and Helen.
=> Calculator content changes

public/robots.txt
=> Ensure all Tesco hubs are disallowed

content/pension_summary/final.cy.md, content/pension_summary/final.en.md
This is for the pension summary feedback.
=> Add link to exit poll survey

app/views/locations/_location.html.erb
Display the link to alternatively book a phone appointment when a
location has no availability.
=> Link to phone appointments

app/views/pension_summaries/summary.html.erb, config/locales/pension_summaries.cy.yml, config/locales/pension_summaries.en.yml, content/pension_summary/final.cy.md, content/pension_summary/final.en.md
This positions the exit poll more prominently and should result in more
completed polls.
=> Improve positioning of self-serve exit poll

content/pension_types.cy.md, content/pension_types.en.md, content/state_pension.cy.md, content/state_pension.en.md
Updates the rates expressed throughout the website content per the new
financial year's rates.
=> Update the state pension rates per 2018-2019

app/controllers/guides_controller.rb, app/views/questions/_pension_start_year_question.html.erb, app/views/questions/_yes_no_dont_know_question.html.erb, config/locales/cy.yml, config/locales/en.yml
Adds further translated strings for the options and buttons in the Pension Type
Tool journey.
=> Translations for Pension Type Tool

Gemfile.lock, content/pension_summary/get_an_adjustable_income.cy.md, content/pension_summary/get_an_adjustable_income.en.md
This subtly changes the text around time restrictions with adjustable
income products.
=> Remove time restriction from adjustable income

content/privacy.cy.md, content/privacy.en.md
Includes the updated privacy notice with GDPR compliance. Also includes
Welsh translation.
=> Privacy notice GDPR

Gemfile.lock, content/pension_summary/final.cy.md, content/pension_summary/final.en.md
=> Add privacy notice to pension summary

app/controllers/booking_requests_controller.rb, app/forms/booking_request_form.rb, app/lib/booking_requests/api_mapper.rb, app/views/booking_requests/step_two.html.erb, features/pages/booking_step_two.rb, features/step_definitions/customer_booking_request_steps.rb, spec/cassettes/BookingRequests_Api/_create/when_the_request_is_successful/returns_true.yml, spec/forms/booking_request_form_spec.rb, spec/lib/booking_requests/api_mapper_spec.rb, spec/lib/booking_requests/api_spec.rb
Ensures we capture the customer's contact consent during the
face-to-face booking journey.
Synchronise release with guidance-guarantee-programme/planner#253
=> GDPR compliance for face-to-face journey

CONTRIBUTING.md, app/models/telephone_appointment.rb, spec/models/telephone_appointment_spec.rb
calculate age at the time of the appointment/slot rather than the current time
=> 527 age at phone appointment

app/views/booking_requests/step_two.html.erb
Display this help text to describe SMS reminders.
=> Customer SMS help text

.travis.yml, Gemfile.lock, app/views/booking_requests/step_two.html.erb, app/views/telephone_appointments/_step_3.html.erb, app/views/tesco/bookings/_step_3.html.erb
Labels the `phone` fields and help text consistently across the booking journey
channels.
=> Label phone field consistently

app/assets/javascripts/application.js, app/controllers/welsh_language/booking_requests_controller.rb, app/lib/welsh_language.rb, app/lib/welsh_language/api.rb, app/lib/welsh_language/mapper.rb, app/models/welsh_language/booking_request.rb, app/views/welsh_language/booking_requests/completed.html.erb, app/views/welsh_language/booking_requests/new.html.erb, config/locales/cy.yml, config/routes.rb, content/appointments.cy.md, features/pages/welsh_language_booking_completed.rb, features/pages/welsh_language_booking_request.rb, spec/cassettes/Welsh_language_bookings/Customer_attempts_to_place_an_invalid_booking_request.yml, spec/cassettes/Welsh_language_bookings/Customer_places_a_face-to-face_booking_request_successfully.yml, spec/cassettes/Welsh_language_bookings/Customer_places_a_telephone_booking_request_successfully.yml, spec/features/welsh_language_booking_spec.rb, spec/lib/welsh_language/mapper_spec.rb, spec/models/welsh_language/booking_request_spec.rb
Adds a simple booking journey for Welsh language appointments.
=> Add Welsh language customer booking journey

app/views/components/_webchat.html.erb, config/initializers/govspeak.rb, content/pension_type_tool.en.md, content/pension_type_tool/defined_contribution.en.md, content/pension_type_tool/might_defined_contribution.en.md, content/pension_type_tool/most_cases_defined_benefit.en.md, content/pension_type_tool/most_cases_defined_contribution.en.md, content/pension_type_tool/question_1.en.md, content/pension_type_tool/question_2.en.md, content/pension_type_tool/question_3.en.md, content/pension_type_tool/question_4.en.md, content/privacy.en.md
When the customer has javascript enabled (the tool requires javascript)
we display a link to the TPAS webchat tool.
=> Link to TPAS webchat in pension type tool

app/assets/javascripts/application.js, app/assets/stylesheets/components/_sfgb-banner.scss, app/views/home/show.html.erb, content/appointments.cy.md, content/appointments.en.md, content/privacy.cy.md, content/privacy.en.md
Display temporary SFGB notices before the transition is completed.
=> SFGB banners

app/views/booking_requests/_booking_request_confirmation.html.erb
Reverts guidance-guarantee-programme/pension_guidance#1124
=> Revert "Alter confirmation for Christmas period"

app/lib/booking_requests/api.rb
Faraday is particular about these values so they need to be coerced.
=> Coerce configured values to numerics

content/appointments.cy.md, content/appointments.en.md
This is no longer needed as the transition has occurred.
=> Remove SFGB privacy notice

content/after_your_appointment.en.md
Added further content regarding fixed term annuities.
=> Simple content update

content/privacy.en.md
Some minor alterations to the content of our privacy notice.
=> Update privacy notice with latest details

config/locales/cy.yml
This brings it inline with the experiment elsewhere.
=> Update Welsh homepage title

content/pension_type_tool.cy.md, content/pension_type_tool.en.md
This was deemed unnecessary so can be removed.
=> RNIB Issue 6: Before you start placement

app/views/locations/search.html.erb
This was made obsolete by realtime availability.
=> Remove redundant passage

app/controllers/booking_requests_controller.rb, app/forms/booking_request_form.rb, spec/requests/error_pages_spec.rb
This was erroring before but should 404 instead.
=> 404 for missing locations

app/assets/javascripts/application.js, app/views/pension_summaries/about_you.html.erb, config/locales/pension_summaries.cy.yml, config/locales/pension_summaries.en.yml, content/pension_summary/about_you.en.md
This was confusing for some customers as it appeared mandatory in all
instances. These changes ensure the customer is aware these fields are
opt-in.t
=> Clarify the customer research fields

app/forms/booking_request_form.rb, app/models/telephone_appointment.rb, app/views/booking_requests/step_two.html.erb, app/views/telephone_appointments/_step_3.html.erb, config/locales/en.yml, features/step_definitions/telephone_booking_request_steps.rb, spec/forms/booking_request_form_spec.rb, spec/models/telephone_appointment_spec.rb
Ensure the customer enters additional information when they specify they
need accessibility adjustments or help with their appointment.
=> Makes notes required for accessibility adjustments

Gemfile.lock, content/trusted_sources.cy.md, content/trusted_sources.en.md
Ensure we signpost off to the correct drawdown calculator as MAS.
=> Update signposting links

app/assets/stylesheets/components/_maps-header.scss, app/assets/stylesheets/layout/_common_page_structure.scss, app/views/layouts/_base.html.erb
Adds the new MAPS header banner across the website.
=> Add the MAPS banner to headings

app/controllers/employer/bookings_controller.rb, app/domain/breadcrumb.rb, app/models/employer/booking.rb, config/routes.rb
The employer was defaulting to Tesco when displaying breadcrumbs.
=> Explicitly pass employer

app/assets/javascripts/components/Navigation.es6, app/assets/javascripts/components/Slider.es6, app/forms/booking_request_form.rb, app/models/employer/booking.rb, app/models/telephone_appointment.rb, app/views/booking_requests/step_two.html.erb, app/views/calculators/adjustable_income/_estimate.html.erb, app/views/calculators/leave_pot_untouched/_estimate.html.erb, app/views/calculators/take_cash_in_chunks/_estimate.html.erb, app/views/components/_slider.html.erb, app/views/employer/bookings/_step_3.html.erb, app/views/pension_summaries/step_two.html.erb, app/views/pension_summaries/summary.html.erb, app/views/telephone_appointments/_step_3.html.erb, app/views/telephone_appointments/_times.html.erb, config/locales/calculators/leave_pot_untouched.en.yml, config/locales/cy.yml, config/locales/en.yml, features/step_definitions/calculator_steps.rb, spec/forms/booking_request_form_spec.rb, spec/models/telephone_appointment_spec.rb
See individual commits for details.
=> The RNIB issues that have been approved

app/lib/locations/location.rb, app/lib/locations/repository.rb, app/views/locations/show.html.erb, features/fixtures/locations.json, features/pages/location_page.rb, features/step_definitions/location_steps.rb, spec/fixtures/locations.json, spec/lib/locations/repository_spec.rb
When access information is assigned to a face-to-face location we ought
to display it during the customer's booking journey.
=> Display access information when provided

app/views/locations/show.html.erb
=> Place under a heading instead

Gemfile.lock, content/trusted_sources.cy.md, content/trusted_sources.en.md
Also bumps the output templates for the same reason.
=> Add PLSA to trusted sources

Gemfile.lock, content/trusted_sources.cy.md, content/trusted_sources.en.md
This was incorrectly copied so has now been corrected.
=> Correct PLSA content

content/privacy.en.md
Changes to accommodate the need for recording guidance sessions and
various other necessary changes.
=> Update privacy policy

app/views/contact/new.html.erb, app/views/feedbacks/_feedback_form.html.erb, app/views/feedbacks/new.html.erb, config/initializers/govspeak.rb, features/customer_booking_request.feature, spec/features/complaint_spec.rb, spec/features/feedback_spec.rb, spec/features/questions_spec.rb
Reverts guidance-guarantee-programme/pension_guidance#1228
=> Revert "Temporarily remove inline zendesk feedback"

app/views/booking_requests/step_one.html.erb, app/views/employer/bookings/_step_1.html.erb, app/views/telephone_appointments/_step_1.html.erb, content/appointments.en.md, content/book_face_to_face.en.md, content/book_phone.en.md
Appointment availability is currently being affected by the ongoing
health crisis.
=> Add availability banner notices

app/views/locations/_location.html.erb, app/views/locations/index.html.erb, content/appointments.en.md, content/book_face_to_face.en.md, content/book_phone.en.md, features/customer_booking_request.feature, features/find_nearest_face-to-face_appointment_locations.feature, features/view_face-to-face_appointment_location_details.feature, spec/features/agent_bookings_spec.rb
Stops customers following dead end journeys for face-to-face locations
since they're currently not offering availability due to the ongoing
health crisis.
=> Hide face-to-face channel where possible

content/pension_types.en.md, content/state_pension.cy.md, content/state_pension.en.md
This brings parity with the GOVUK guidance on the same content.
=> Round up state pension amounts

public/google17262c9534571986.html
Requested temporarily by Sean C.
=> Add Google verification

Gemfile, Gemfile.lock, app/controllers/contact_controller.rb, app/views/contact/new.html.erb, config/initializers/recaptcha.rb, spec/features/complaint_spec.rb
This has been subject to spam for some time now so hopefully a recaptcha
test will mitigate.
=> Block bot complaint submissions

config/locales/calculators/take_cash_in_chunks.en.yml, config/locales/calculators/take_whole_pot.en.yml
Several guiders have mentioned that this would serve Scottish customers
better.
=> Update signposting to tax estimate

Gemfile, Gemfile.lock, lib/tasks/export.rake
Exports a CSV containing all entries to azure block blob storage, to be
run nightly.
=> Export pension summaries to azure blob storage

app/controllers/telephone_appointments_controller.rb, app/models/telephone_appointment.rb, app/views/telephone_appointments/confirmation.html.erb, app/views/telephone_appointments/ineligible.html.erb, app/views/telephone_appointments/new.html.erb
Phone appointments now track a 'funnel' from new to either ineligible or
complete. For the ineligible step we also pass the reason(s) for
ineligibility.
=> Process extra dimensions for phone appointments

app/views/calculators/take_cash_in_chunks/_form.html.erb, app/views/calculators/take_whole_pot/_form.html.erb, config/locales/calculators/take_cash_in_chunks.cy.yml, config/locales/calculators/take_cash_in_chunks.en.yml, config/locales/calculators/take_whole_pot.cy.yml, config/locales/calculators/take_whole_pot.en.yml
=> Wording changes to calculators

content/divorce.cy.md, content/divorce.en.md
=> Reposition recently added content

categories/your_pension_details.en.yml, config/locales/cy.yml, config/locales/en.yml, content/adjustable_income.en.md, content/appointments.en.md, content/benefits.en.md, content/divorce.en.md, content/financial_advice.en.md, content/guaranteed_income.en.md, content/living_abroad.en.md, content/pension_pot_options.en.md, content/pension_statements.en.md, content/pension_types.en.md, content/state_pension.en.md, content/take_cash_in_chunks.en.md, content/take_whole_pot.en.md, content/tax.en.md, content/transfer_pension.en.md, content/when_you_die.en.md, content/work_out_income.en.md, content/your_pension_before_55.en.md
Per requests from the SEO folks.
=> Update page titles and meta descriptions

app/views/home/show.html.erb, config/locales/cy.yml, config/locales/en.yml, content/scam_warning.cy.md, content/scam_warning.en.md
Adds this temporary warning and signposting due to recent scamming.
=> Add a scam warning banner prominently

content/privacy.en.md
These were requested by Helen.
=> Alterations to the privacy policy

app/views/layouts/home.html.erb
This will be deployed during the upcoming homepage experiments.
=> Install anti-flicker on homepage

app/controllers/bsl/bsl_booking_requests_controller.rb, app/lib/bsl.rb, app/lib/bsl/api.rb, app/lib/bsl/mapper.rb, app/lib/welsh_language/api.rb, app/models/bsl/booking_request.rb, app/views/bsl/bsl_booking_requests/completed.html.erb, app/views/bsl/bsl_booking_requests/new.html.erb, app/views/feedbacks/_feedback_form.html.erb, config/locales/en.yml, config/routes.rb, content/appointments.en.md, content/book_phone.en.md, features/pages/bsl_booking_completed.rb, features/pages/bsl_booking_request.rb, spec/cassettes/British_Sign_Language_bookings/Customer_places_a_BSL_booking_request_successfully.yml, spec/features/bsl_booking_spec.rb, spec/models/bsl/booking_request_spec.rb
Allows customers to book a request for a British Sign Language video-based
appointment.
=> Add BSL bookings option

app/views/layouts/home.html.erb
This experiment has concluded.
=> Remove the anti-flicker script

app/controllers/welsh_language/booking_requests_controller.rb, app/lib/welsh_language/mapper.rb, app/models/welsh_language/booking_request.rb, app/views/welsh_language/booking_requests/new.html.erb, content/appointments.cy.md, spec/features/welsh_language_booking_spec.rb, spec/lib/welsh_language/mapper_spec.rb, spec/models/welsh_language/booking_request_spec.rb
Disables Welsh language face-to-face bookings due to COVID-19
restrictions.
=> Temporarily disable face-to-face bookings

Gemfile.lock, content/trusted_sources.cy.md, content/trusted_sources.en.md
The drawdown calculator is being EOL'd.
=> Remove links to MAS calculator

app/views/bsl/bsl_booking_requests/completed.html.erb, app/views/bsl/bsl_booking_requests/new.html.erb, app/views/welsh_language/booking_requests/completed.html.erb, app/views/welsh_language/booking_requests/new.html.erb
Reverts guidance-guarantee-programme/pension_guidance#1307
=> Revert "Add temporary Christmas notice"

config/locales/cy.yml, config/locales/en.yml, content/for_employers.cy.md, content/for_employers.en.md, content/privacy.cy.md, content/privacy.en.md
A temporary change while the issues with the contact@ routing are
resolved.
=> Temporarily replace contact@ with appointments@

config/locales/cy.yml, config/locales/en.yml, content/for_employers.cy.md, content/for_employers.en.md, content/privacy.cy.md, content/privacy.en.md
Reverts guidance-guarantee-programme/pension_guidance#1311
=> Revert "Temporarily replace contact@ with appointments@"

app/controllers/contact_controller.rb, app/models/complaint.rb, app/views/contact/new.html.erb, config/locales/cy.yml, config/locales/en.yml, spec/features/complaint_spec.rb, spec/models/complaint_spec.rb
Makes many improvements to the complaints form, including:
* Accessible labelling and structure
* Improved and accessible error handling and reporting
* Simplifying complaints by removing recaptcha
=> Complaints are inaccessible

Gemfile.lock
The pension tax rules section was being omitted.
=> Ensure the correct sections are included

app/views/telephone_appointments/new.html.erb, features/telephone_booking_request.feature
This reverts commit dc2c62004bc5b855808b2be65d06302bbbc016c9.
=> Revert "Temporarily hide booking calendar"

app/views/application/_ineligible.html.erb, app/views/bsl/bsl_booking_requests/new.html.erb, app/views/pension_summaries/summary.html.erb, app/views/shared/_alternative_journeys.html.erb, app/views/telephone_appointments/_step_3.html.erb, app/views/welsh_language/booking_requests/new.html.erb, content/pension_summary/final.cy.md, content/pension_summary/final.en.md, content/pension_summary/get_a_guaranteed_income.en.md, content/pension_summary/get_an_adjustable_income.cy.md, content/pension_summary/get_an_adjustable_income.en.md, content/pension_summary/leave_your_pot_untouched.cy.md, content/pension_summary/leave_your_pot_untouched.en.md, content/pension_summary/mix_your_options.cy.md, content/pension_summary/mix_your_options.en.md, content/pension_summary/take_cash.cy.md, content/pension_summary/take_cash.en.md, content/pension_summary/take_whole.en.md, content/pension_type_tool/defined_contribution.cy.md, content/pension_type_tool/defined_contribution.en.md, content/pension_type_tool/might_defined_contribution.cy.md, content/pension_type_tool/might_defined_contribution.en.md, content/pension_type_tool/most_cases_defined_benefit.cy.md, content/pension_type_tool/most_cases_defined_benefit.en.md, content/pension_type_tool/most_cases_defined_contribution.cy.md, content/pension_type_tool/most_cases_defined_contribution.en.md
A level from the taxonomy was removed.
=> Correct links for MoneyHelper

app/views/layouts/full_width_widget.html.erb
This code is testable inside AEM here: https://test.moneyhelper.org.uk/en/pensions-and-retirement/pension-wise/find-out-your-pension-type/find-out-your-pension-type
=> Scroll frame to top when page loads

app/lib/where_you_heard.rb
=> Remove redundant WDYH options

Gemfile.lock, config/locales/pension_summaries.cy.yml, config/locales/pension_summaries.en.yml, content/pension_summary/get_a_guaranteed_income.cy.md, content/pension_summary/get_a_guaranteed_income.en.md, content/pension_summary/get_an_adjustable_income.cy.md, content/pension_summary/get_an_adjustable_income.en.md, content/pension_summary/getting_help_with_debt.cy.md, content/pension_summary/getting_help_with_debt.en.md, content/pension_summary/how_my_pension_affects_my_benefits.cy.md, content/pension_summary/how_my_pension_affects_my_benefits.en.md, content/pension_summary/how_my_pension_is_taxed.cy.md, content/pension_summary/how_my_pension_is_taxed.en.md, content/pension_summary/leave_your_pot_untouched.cy.md, content/pension_summary/leave_your_pot_untouched.en.md, content/pension_summary/mix_your_options.cy.md, content/pension_summary/mix_your_options.en.md, content/pension_summary/take_cash.cy.md, content/pension_summary/take_cash.en.md, content/pension_summary/take_whole.cy.md, content/pension_summary/take_whole.en.md, content/trusted_sources.en.md, spec/features/pension_summary_spec.rb
=> Summary document updates for year end

app/decorators/cached_guide_decorator.rb, app/decorators/guide_decorator.rb, app/views/appointment_summaries/new.html.erb, app/views/bsl/bsl_booking_requests/new.html.erb, app/views/contact/new.html.erb, app/views/guides/show.html.erb, app/views/layouts/govuk_template.html.erb, app/views/pension_summaries/about_you.html.erb, app/views/pension_summaries/step_one.html.erb, app/views/telephone_appointments/new.html.erb, app/views/welsh_language/booking_requests/new.html.erb, content/adjustable_income.cy.md, content/adjustable_income.en.md, content/guaranteed_income.cy.md, content/guaranteed_income.en.md, content/leave_pot_untouched.cy.md, content/leave_pot_untouched.en.md, content/pension_type_tool/question_1.cy.md, content/pension_type_tool/question_1.en.md, content/take_cash_in_chunks.cy.md, content/take_cash_in_chunks.en.md, content/take_whole_pot.cy.md, content/take_whole_pot.en.md, public/robots.txt
~~Warning: This PR might be replaced by https://github.com/guidance-guarantee-programme/pension_guidance/pull/1399~~
- Guides and pages can set a canonical and noindex content value
- Set canonical and noindex for multiple pages
- Also add these paths to robots.txt (this has been requested)
=> Update canonicals and noindex values

app/helpers/application_helper.rb, app/views/nudge_appointments/_step_3.html.erb, app/views/nudge_appointments/confirmation.html.erb, app/views/telephone_appointments/nudge.html.erb
This is now online so we can use the correct number.
=> Add stronger nudge IVR number

app/views/nudge_appointments/_step_3.html.erb, app/views/telephone_appointments/_step_3.html.erb
Reverts guidance-guarantee-programme/pension_guidance#1416
These emails are now deliverable.
=> Revert "Add temporary messaging regarding BT internet"

app/views/locations/_location.html.erb, features/customer_booking_request.feature
The booking button should be hidden for regular customers.
=> Hide booking button unless agent

app/controllers/nudge_appointments_controller.rb, app/models/nudge_appointment.rb, app/views/booking_requests/step_two.html.erb, app/views/bsl/bsl_booking_requests/new.html.erb, app/views/employer/bookings/_step_3.html.erb, app/views/nudge_appointments/_hidden_fields.html.erb, app/views/nudge_appointments/_step_3.html.erb, app/views/telephone_appointments/_step_3.html.erb, config/locales/en.yml, features/pages/new_nudge_appointment.rb, spec/features/nudge_appointment_spec.rb, spec/models/nudge_appointment_spec.rb
=> Alter customer research form hint

Gemfile.lock
Updates templates to include new content and guidance for 2023.
=> Bump templates for new year 23 content

config/initializers/redis_pool.rb
This attempts to check a CA otherwise.
=> Fix redis configuration

app/assets/stylesheets/components/slot-picker/_slot-picker-times.scss
=> Correct the alignment of the header

app/views/telephone_appointments/new.html.erb, app/views/welsh_language/booking_requests/completed.html.erb, app/views/welsh_language/booking_requests/new.html.erb
Corrections to Adobe data attributes.
=> ACDL corrections

app/assets/stylesheets/components/_calculator.scss, app/assets/stylesheets/money-helper-variables.scss, app/views/calculators/_form_input_currency.html.erb
This still works in the regular embedded contexts across MoneyHelper but adds some additional improvements to better match the PWD needs.
=> Style calculators for embedding in PWD

app/views/bsl/bsl_booking_requests/completed.html.erb, app/views/bsl/bsl_booking_requests/new.html.erb, app/views/welsh_language/booking_requests/completed.html.erb, app/views/welsh_language/booking_requests/new.html.erb
These were incorrectly constricted to a narrow view.
=> Improve layout for alternative journeys

app/helpers/application_helper.rb, app/views/telephone_appointments/_step_3.html.erb, app/views/telephone_appointments/confirmation.html.erb, spec/features/due_diligence_booking_spec.rb
This is from feedback via international customers.
=> Display timezone against selected times
