Gemfile, Gemfile.lock
Removes invalid UTF-8 characters from the environment so the app doesn't choke on them.
=> Prevent "invalid byte sequence in UTF-8" errors

app/controllers/application_controller.rb, config/environments/staging.rb, config/secrets.yml
Introduces a new environment - staging - that inherits from production. This is primarily so that we can run a staging application with `RAILS_ENV=staging` and differentiate log streams, performance monitoring etc.
Removes any `Rails.env.production?` anti-patterns.
=> Add staging environment

Gemfile, Gemfile.lock, config/initializers/timeout.rb
It's causing massive instability on Heroku
=> Remove Rack::Timeout

config/routes.rb
Remove duplicated controller and path details.
Reduces width buts adds height to the code so it's up for discussion wether or not it's a worthwhile change.
=> Refactor styleguide routes

app/controllers/styleguide_controller.rb
Don't need to repeat the layout name in the calls to `render`
=> Refactor style guide controller

content/benefits.md, content/complaints.md, content/divorce.md, content/living_abroad.md, content/pension_complaints.md, content/pension_pot_options.md, content/pension_types.md, content/scams.md, content/tax.md
Guides that do not have this extra space confuse the govspeak parser causing it to not recognise headers properly. [Setext VS Atx-style headers](http://daringfireball.net/projects/markdown/syntax#header) ?
=> Add extra space between front matter and markdown content.

app/controllers/application_controller.rb
In production we have seen a few CORS requests using the HTTP `OPTIONS` verb. These are generating a 500 error because a `ActionController::InvalidAuthenticityToken` was being throw when we try and gracefully render a 404 page.
This change provides an empty session if CSRF token is invalid for the request but doesn't reset it completely. Used as default if `:with` option is not specified.
=> Provide an empty session if CSRF is invalid

app/views/home/show.html.erb
We don't want to increase the volume of calls to these organisations during the mass media campaign.
=> Remove the referral to TPAS and MAS for DB info

app/controllers/guides_controller.rb, app/views/home/show.html.erb, content/when_you_die.md, features/step_definitions/guide_steps.rb
- Adds ‘Your pension when you die’ to homepage
- Adds ‘Your pension when you die’ as a related link for journey content
- Use relative links for ‘Your pension when you die’ to allow it to work across environments
Discussed with @raykhan66
=> When you die linking

app/controllers/guides_controller.rb, app/decorators/cached_guide_decorator.rb, app/decorators/guide_decorator.rb, spec/decorators/cached_guide_decorator_spec.rb, spec/decorators/guide_decorator_spec.rb
This caches the `title` and `content` attributes of instances of `GovspeakGuideDecorator`
=> Cache govspeak

app/views/guides/show.html.erb
Rendering a guide page is the slowest part of the app:
Turns out half the time taken to display a guide page is spent rendering the journey navigation partial:
Caching this single partial dramatically speeds up rendering time.
Something to consider before this goes in is that the default Rails cache [uses the filesystem](http://guides.rubyonrails.org/caching_with_rails.html#activesupport-cache-filestore) and never expires(!)
=> Cache journey nav partial for each guide

config/routes.rb
We have an unconventional staging environment within the application so the previous conditional was not expansive enough.
=> Only mount Jasmine in development

config/environments/test.rb
A content change had caused a build to break in CI
Addresses #188
=> Disable caching in test environment

config/cucumber.yml, features/find_nearest_face-to-face_appointment_locations.feature, features/view_face-to-face_appointment_location_details.feature
Add features for locating face-to-face appointment locations, which won't be run currently as they are tagged with `@todo`.
=> CAB locator features

content/appointments.md
The idea is to get this description into the sitelink that Google generates. Google sitelinks are a black box but it seems that for the _“Book a free appointment”_ sitelink Google uses the meta-description of the page. All other sitelinks use the first H1 and paragraph of the page :santa: 
[“Google is the homepage”](https://gds.blog.gov.uk/2012/01/27/what-does-google-is-the-homepage-mean-irl)
=> Change the meta description of the appointments page.

content/pension_pot_options.md, content/tax.md, content/when_you_die.md
Changes introduced by #161 caused anchor links to stop working. These changes fix that and updates language to reflect new definitions.
=> Fix anchor links to options content

app/assets/stylesheets/components/_highlighted-info.scss, app/assets/stylesheets/lib/_variables.scss
Safari on iPhone adds an `<a href=tel:…>` to anything it recognises as a phone number.
cc: @aduggin
=> Style phone number on iPhone.

app/views/layouts/_base.html.erb
Do we want to include logic to exclude by environment? We don't for Google Tag Manager.
=> Add UserZoom JavaScript tracking codes

content/cookies.md
GOV.UK now use Universal Analytics and explain what the Universal Analytics cookies are for. It makes sense for us to adopt the same language.
=> Use GOV.UK Universal Analytics cookie text

app/assets/stylesheets/components/_options-overview.scss, app/assets/stylesheets/lib/_variables.scss, content/pension_pot_options.md
We believe that users are currently confusing this section with the list of options.
Before:
After:
=> Visually separate ‘Compare your options’ heading

config/initializers/gc_profiling.rb
Setting `ENABLE_GC_PROFILING` in the environment will enable garbage collection instrumentation. Hoping to get some insight into the occasional slowness, and occasional failure-to-exit errors. This will push GC timing to New Relic.
see: https://docs.newrelic.com/docs/agents/ruby-agent/features/garbage-collection#gc_setup
=> Optionally enable garbage collection profiling

app/assets/stylesheets/components/_location-list.scss, app/assets/stylesheets/components/_locator-promo.scss, app/controllers/styleguide_controller.rb, app/views/styleguide/components.html.erb, app/views/styleguide/components/_highlighted_info.html.erb, app/views/styleguide/components/_locator_link_promo.html.erb, app/views/styleguide/components/_locator_promo.html.erb, app/views/styleguide/index.html.erb, app/views/styleguide/pages/locator_entry.erb, app/views/styleguide/pages/locator_invalid.erb, app/views/styleguide/pages/locator_location.erb, app/views/styleguide/pages/locator_results.erb, config/routes.rb
The styleguide now has static versions of the following locator pages:
Locator entry page
/styleguide/pages/locator-entry
Locator results page
/styleguide/pages/locator-results
Locator no results page
/styleguide/pages/locator-invalid
Locator location page
/styleguide/pages/locator-location
=> Styleguide locator

lib/locations/location.rb, lib/locations/repository.rb, spec/fixtures/locations.json, spec/lib/locations/location_spec.rb, spec/lib/locations/repository_spec.rb, spec/lib/locations/search_result_spec.rb, spec/lib/locations/search_spec.rb
Generating a slug for each location based on its title is too brittle. We know location titles will change. If that happens previously addressable locations will no longer be addressable.
The GeoJSON specification supports an ID attribute for each location. By using that we can be continue to address a location if its title changes.
***These needs updated cassettes before merging.***
=> [WIP] Use the GeoJSON Feature ID to identify locations

app/controllers/locations_controller.rb, spec/controllers/locations_controller_spec.rb
This view will need the search form added to it but will mean people can browse to `/locations`:
=> Don't redirect when no postcode supplied

features/fixtures/locations.json, lib/locations/location.rb, lib/locations/repository.rb, spec/fixtures/locations.json, spec/lib/locations/location_spec.rb, spec/lib/locations/repository_spec.rb, spec/lib/locations/search_result_spec.rb, spec/lib/locations/search_spec.rb
Generating a slug for each location based on its title is too brittle. We know location titles will change. If that happens previously addressable locations will no longer be addressable.
The GeoJSON specification supports an ID attribute for each location. By using that we can be continue to address a location if its title changes.
=> Use the GeoJSON Feature ID to identify locations

app/views/locations/show.html.erb
Linking to the “What you’ll get from the appointment” heading is more useful to the user since all content before that on the page is about phone booking and who can book.
cc/ @alexkouz @aduggin
=> Link to relevant appointment content from location profile

lib/geocoder.rb, spec/lib/geocoder_spec.rb
`UKPostcode` will let through `SW18 0QE` which doesn't exist so we can't give it sole responsibility for catching invalid postcodes and it no longer makes sense to have two possible exceptions raised.
#269
=> Handle postcodes having the correct form but not actually existing

config/initializers/assets.rb
The SASS in the `govuk_elements` bower component refers to [/assets/icons/icon-pointer.png](https://github.com/alphagov/govuk_elements/blob/master/govuk/public/images/icons/icon-pointer.png) when compiled but the same file is also provided by the `govuk_frontend_toolkit` gem at [/assets/icon-pointer.png](https://github.com/alphagov/govuk_frontend_toolkit/blob/master/images/icon-pointer.png) which is what ends up in the compiled assets.
Put the bower component asset path before those of the gem so the correct url is used in the compiled stylesheet.
=> Put GOV.UK Elements assets at start of asset pipeline load path

.jscsrc
https://github.com/jscs-dev/node-jscs/issues/993
=> `validateJSDoc` has been deprecated from JSCS, remove it

spec/requests/styleguide_spec.rb
[`styleguide/components.html.erb`](https://github.com/guidance-guarantee-programme/pension_guidance/blob/8a640f1e1cfaf0d9c4e08ffe073d59305d498d66/app/views/styleguide/components.html.erb#L9) refers to `styleguide/components/_locator_promo.html.erb` which was deleted in 96939d8c1ad7c84675f3bc0a444d27628bd9a48e and is causing a 500 @aduggin
=> Check that each styleguide page gives a 200

app/assets/stylesheets/components/_journey-overview.scss, app/assets/stylesheets/components/_options-overview.scss, content/6_steps_you_need_to_take.html, content/pension_pot_options.md
Switching from subtle heading links to more obvious 'More on ...' links on the '6 steps' and 'Options' index page
=> Landing page links

app/controllers/application_controller.rb, app/controllers/concerns/breadcrumbs.rb, app/controllers/guides_controller.rb, app/controllers/locations_controller.rb, app/domain/breadcrumb.rb, app/views/components/_breadcrumbs.html.erb, features/pages/location_page.rb, features/step_definitions/location_steps.rb, spec/controllers/concerns/breadcrumbs_controller_concern_spec.rb, spec/controllers/locations_journey_breadcrumbs_spec.rb, spec/domain/breadcrumb_spec.rb
The breadcrumb titles will probably need to be changed, and I'm certain there'll be feedback on the code,  but behold.
=> Locations journey breadcrumbs

app/controllers/locations_controller.rb, app/views/locations/index.html.erb, app/views/locations/show.html.erb, features/cassettes/View_face-to-face_appointment_location_details/From_search_results.yml, features/pages/location_page.rb, features/step_definitions/location_steps.rb, features/view_face-to-face_appointment_location_details.feature
"Back to results" is displayed if there's a `postcode` query string param.
Interested in your opinion on the Gherkin @andrewgarner.
=> Locations back to results link

app/views/layouts/_base.html.erb
If a webpage does not specify a browser configuration file, IE11+ automatically looks for "browserconfig.xml" in the root directory of the server. To prevent this, use an "msapplication-config" header with the content attribute to "none". See https://msdn.microsoft.com/en-us/library/dn320426(v=vs.85).aspx
=> Tell IE11+ there is no "browserconfig.xml"

content/take_cash_in_chunks.md
This is to keep consistent with appointment content and to make sure users know that providers may refer to chunks in this way.
=> UFPLS line added

Rakefile
The fix introduced in 0372f76226c1171b88b93e36f372b5764c901993 was reverted in c9bcc895407e7c8180094af410e5b9a23378250e, however running `rake spec:javascript` locally now breaks. Revert it.
Any opinions @andrewgarner ?
=> Revert "Remove rake task fix for jasmine"

app/controllers/locations_controller.rb, app/views/locations/failed_lookup.html.erb, lib/geocoder.rb, spec/controllers/locations_controller_spec.rb, spec/lib/geocoder_spec.rb
Addresses #322 
The specific exception we've seen raised in production is `Excon::Errors::Timeout` but this covers anything being raised.
Too crude @andrewgarner ? Are we ok with rendering the _xxx is not a valid postcode_ page when this occurs?
=> Handle Postcodes::IO lookup timeouts

app/controllers/search_results_controller.rb, app/views/search_results/index_error.html.erb, config/locales/en.yml, spec/controllers/search_results_controller_spec.rb
Google Custom Search Engine has been giving us [a few 5xx errors this last while](https://bugsnag.com/hm-treasury-1/pension-guidance/errors/55e6f68688f8ad5351666b96).
Rendering the search form again on the error page would allow the user to manually retry the search if desired:
=> Search results error page

config/initializers/resolv.rb
We've had [a few failed DNS lookups](https://bugsnag.com/hm-treasury-1/pension-guidance/errors/56096ff402c5eb752121b3d6) as described [in this post](http://blog.gregburek.com/2015/02/22/dns-eglibc-and-resolv-replace-on-heroku/).
We can give this a spin for a while and see if the problem disappears.
=> Don't depend on system for DNS resolution

app/assets/stylesheets/components/_player-container.scss
Varible scoping within the `media-player` mixin caused a similar problem to what was solved with https://github.com/guidance-guarantee-programme/pension_guidance/commit/dea46e6195ddfd8e2fb637c4044af536426690cd.
This change solves the 404 on the volume icon and removes the need to redefine the images for the other controls:
=> Use correct asset paths for media player

app/decorators/location_decorator.rb, spec/decorators/location_decorator_spec.rb
Shouldn't happen but handle it when it does happen, see [this bugsnag I created](https://bugsnag.com/hm-treasury-1/pension-guidance/errors/561ccf3502c5eb75213edadd) whilst checking something else out.
=> Handle the location not being present in the nearest locations

spec/lib/switchboard_spec.rb
The connection was lingering around and causing tests hitting `LocationsController#show` to fail whenever they were ran after.
Failure demonstrated with:
```
rspec ./spec/lib/switchboard_spec.rb ./spec/controllers/locations_journey_breadcrumbs_spec.rb:48 --seed 64399
```
=> Disable `Switchboard` lookups after testing

config/initializers/assets.rb
We've had a small trickle of 404s for one of the `govuk_elements` assets:
__elements/_elements-typography.scss__ pulls in [icon-arrow-left.png](https://github.com/alphagov/govuk_elements/blob/32009ec34756d0acc95350b12a276cbe726f3de6/public/sass/elements/_elements-typography.scss#L235) from [public/images](https://github.com/alphagov/govuk_elements/tree/master/public/images) which wasn't being picked up by Sprockets.
=> Add asset from `govuk_elements` to precompile list

app/views/take_whole_pot_calculator/_results.html.erb
This is perhaps the cause of the problem Jim has reported. See:
http://www.simoahava.com/gtm-tips/datalayer-declaration-vs-push/
=> Don't override `window.dataLayer` if it already exists

content/adjustable_income.md, content/guaranteed_income.md, content/mix_options.md, content/take_cash_in_chunks.md, content/take_whole_pot.md
Some of the options pages had hyphens where there should have been dashes. These have been fixed. I've also tidied some copy, eg the annuity page has had some headers updated and the list of annuity types.
=> Hyphen errors on options pages

content/tax.md
Our partners have noticed an error – reference to cash in chunks removed from 'Take your lump sum in one go' section.
=> Error on tax page

content/pension_complaints.md
Text change on making a complaint and link to Citizens Advice removed.
=> Broken link on pension complaints page

app/assets/stylesheets/components/_next-steps.scss, content/adjustable_income.md, content/guaranteed_income.md, content/leave_pot_untouched.md, content/mix_options.md, content/take_cash_in_chunks.md, content/take_whole_pot.md
This follows the current colour scheme, so does not include the new option colours. They will come as part of #391 
This can therefore be merged independently.
=> Adds `next-steps` component and applies to content pages

content/leave_pot_untouched.md
Moved 2nd paragraph up to be part of 1st para. Changed 'can' to 'could' in 2nd sentence.
Deleted 3rd sentence 'Your pension pot could grow further and give you a larger amount of money to last for a shorter amount of time.'
Added 3 bullet points under 2nd sentence.
Added %scams warning below new bullet points.
Changed '## Tax when you leave your whole pot untouched' to '##Tax'
Changed 'As long as your money stays in your pension pot you don’t pay tax on it.' to 'You don’t pay tax while the money stays in your pot.'
Changed 'Whatever money you leave in your pension pot you can [pass on]' to 'Money you leave in your pot can be [passed on]'
Heading '## Charges and investment risk' changed to 'Fees and investment risk'
Split 'Your provider may charge you administration fees for managing the …
=> Changes to Leave_pot_untouched.md

app/controllers/guides_controller.rb, app/decorators/guide_decorator.rb, app/models/guide.rb, app/repositories/guide_repository.rb, content/adjustable_income.md, content/appointments.md, content/book.md, content/guaranteed_income.md, content/leave_pot_untouched.md, content/mix_options.md, content/take_cash_in_chunks.md, content/take_whole_pot.md, spec/fixtures/the_test_govspeak_guide.md, spec/fixtures/the_test_html_guide.html, spec/models/guide_spec.rb
Avoids continually having to hardcode page id's to manipulate views
=> Tags in content frontmatter

app/assets/stylesheets/components/_book-appointment.scss, app/controllers/guides_controller.rb, app/helpers/application_helper.rb, app/helpers/guides_helper.rb, app/helpers/locations_helper.rb, app/views/layouts/_two_column.erb, config/application.rb, features/step_definitions/guide_steps.rb
Appears on `two-column` template and is compatible with both the current and new (dropdown nav) headers.
=> Adds `book a free appointment` link

content/contact.md
Acronym removed as name referred to only once on page no not needed.
=> Update 'Contact us' page

app/views/guides/option.html.erb, content/adjustable_income.md, content/guaranteed_income.md, content/leave_pot_untouched.md, content/mix_options.md, content/take_cash_in_chunks.md, content/take_whole_pot.md
Where possible we should avoid presentation markup in our content files.
=> Render option circles in view not content

app/decorators/govspeak_guide_decorator.rb, app/decorators/guide_decorator.rb, app/decorators/html_guide_decorator.rb, content/take_whole_pot.md, spec/decorators/guide_decorator_spec.rb
Always extract headers from HTML content. This ensures we can also find headers in HTML derived from Govspeak, even if there is embedded HTML in the markdown content.
=> Simplify extraction of guide headers

app/views/calculators/_error_summary.html.erb, app/views/calculators/take_whole_pot/_form.html.erb, config/initializers/govspeak.rb, content/take_whole_pot.md
This removes duplication and makes the markdown content easier to understand.
:fireworks:
=> Render take whole pot calculator form from content

content/tax.md
Changed pension recycling information in line with new fact checks from HMRC. Took out factually incorrect information. Shortened the information to just the basics because the detail of the information is too confusing to understand on a web page. Guidance is to see a financial adviser if you're thinking of paying in money to your pension at the same time as taking it out.
=> Changes to Tax.md

app/forms/take_whole_pot_calculator_form.rb, app/views/calculators/_error_summary.html.erb, app/views/calculators/_form_input_currency.html.erb, app/views/calculators/take_whole_pot/_form.html.erb, config/locales/en.yml, spec/forms/take_whole_pot_calculator_form_spec.rb
If there are multiple errors for an attribute we should show them, however, we can display error messages that give more context about the specific error instead of just using the same error messages for all validation errors.
=> Improve calculator error handling

content/pension_pot_options.md
Hyphens changed to dashes and 'a quarter' changed to '25%' to aid comprehension.
=> Edits to pension pot options page

content/guaranteed_income.md
In the types of annuity table, separated out fixed term and guaranteed period, added short term - following a query raised by TPAS that having guaranteed period and fixed term together was misleading. Policy agreed.
=> Changes to guaranteed_income.md

content/already_bought_annuity.md
Typo fixed, comma removed as not needed, word 'services' removed from Citizens Advice name.
=> Updates to already bought annuity page

content/leave_pot_untouched.md
Redrafted text and moved calculator after testing showed users were confused by mixed messaging of 'leave untouched' and 'pay in'.
Would also like to add a 3rd bullet to in-calculator text:
- You must leave your whole pot – if you take a 25% tax-free lump sum, you must take the rest of your money within 6 months, using one of the [other pension options](/pension-pot-options).
=> Redrafted text and moved calculator

app/domain/taxonomy.rb, content/pension_pot_options.md, content/pension_recycling.md, content/tax.md, features/guides.feature
Changes to the 'Tax you pay on your pension' and 'What you can do with your pension pot' pages.
New page 'Pension recycling'.
'Pension recycling page needs to sit under the 'More' tab on the navigation.
There might be a couple of pension recycling page files. The first file I created, I didn't put the .md on the end. So I redid it.
=> Tax page changes

Gemfile
Load the configured Ruby version via the `.ruby-version` file to ensure
that is the single source of truth.
See guidance-guarantee-programme/location-register#6 for precedent.
=> Make `.ruby-version` the canonical Ruby version

app/views/calculators/_form_input_currency.html.erb
Ensure screen readers will read out both the label and currency symbol for these fields.
=> Improve screen reader labelling for currency fields

Gemfile, Gemfile.lock, app/decorators/category_decorator.rb, app/decorators/govspeak_guide_decorator.rb, app/decorators/guide_decorator.rb, app/decorators/html_guide_decorator.rb, app/view_models/navigation.rb
Drops the Draper dependency in favour of PORO decorators. Draper seems pretty
dormant and likely won't be supporting the imminent Rails 5 release any time
soon.
It seems most of our decorators favour `SimpleDelegator` over Draper too, so
this also brings some consistencies.
=> Replace Draper decorators with POROs

Gemfile, Gemfile.lock, app/assets/javascripts/calculators.js, spec/javascripts/calculatorSpec.js
Previously users had to hit enter or click outside the text field after changing the value of the slider. This PR adds test coverage and ensures that the form is updated on key change.
=> Refresh calculator results when slider text input is changed

app/helpers/calculators_helper.rb, app/views/calculators/leave_pot_untouched/_estimate.html.erb, app/views/calculators/take_cash_in_chunks/_estimate.html.erb
* Visually highlight numbers on the Take cash in chunks and Leave your pot untouched calculators
* Provide a fallback slider maximum when a zero monthly contribution is provided
=> Visually highlight numbers on change

lib/adjustable_income_calculator.rb
The reality is drawdown can last for many years, or even
infinitely. But as this calculator is to illustrate how this
option works, we limit this number to an age of 120. Previously,
we showed (for example) "your income could last until you're 161"
– which can seem confusing.
=> Cap income lasting to 120 on adjustable income calculator

app/views/locations/show.html.erb, config/initializers/enabled_online_booking_locations.rb, features/customer_booking_request.feature, features/fixtures/booking_locations.json, features/pages/location_page.rb, features/step_definitions/customer_booking_request_steps.rb, lib/locations.rb
This acts as a dumb feature flag for now. When the
`online_booking_location_uids` are specified, the corresponding locations are
enabled for online bookings and the start button is displayed to the customer.
=> Configurable online booking locations

app/views/locations/show.html.erb, features/step_definitions/location_steps.rb, features/view_face-to-face_appointment_location_details.feature
We removed all the sidebar navigation a while back, but
this bit must have been missed. It was also pointing some pages
that no longer exist.
=> Remove sidebar navigation on location page

app/controllers/guides_controller.rb, app/decorators/guide_decorator.rb, app/helpers/guides_helper.rb, app/models/guide.rb, app/views/guides/_journey_links.html.erb, app/views/guides/_option.html.erb, app/views/guides/show.html.erb, features/journey_navigation.feature, features/pages/guide_page.rb, features/step_definitions/guide_steps.rb
The next and previous links have been added to the bottom of the calculator pages.
The implementation would allow the buttons to be added to any guide page
as it uses the Taxonomy class to determine the current guide pages position in 
the navigation tree.
=> Next and previous buttons

app/assets/stylesheets/vendor/_slot-picker.scss, app/helpers/booking_requests_helper.rb, app/views/booking_requests/step_one.html.erb, app/views/booking_requests/step_two.html.erb
To ensure the customer can see what times they have chosen before
submitting the remainder of their details. They also have the option
to go back and change the slots using the link provided.
=> Show chosen appointment slots on step two of booking request

app/forms/booking_request_form.rb, app/views/booking_requests/step_two.html.erb, features/pages/booking_step_two.rb, features/step_definitions/customer_booking_request_steps.rb, lib/booking_requests/api_mapper.rb, spec/forms/booking_request_form_spec.rb, spec/lib/booking_requests/api_mapper_spec.rb, spec/requests/complete_booking_request_spec.rb
* Allow validation summary to stretch to full width of container
* Persist radio button values on error state
* Rephrase `dc_pot` question as Yes, no, not sure. Yes and not sure are valid.
@benlovell that change to `dc_pot` might need some thinking on the [planner](https://github.com/guidance-guarantee-programme/planner/blob/master/spec/requests/create_a_booking_request_spec.rb#L74) side of things. Ideally we would store the exact answer the user provided, but I suppose we could coerce to `true` if easier?
=> Online booking customer details page tweaks

app/forms/booking_request_form.rb, lib/booking_requests/api_mapper.rb, spec/lib/booking_requests/api_mapper_spec.rb
The planner API for booking requests expects this now.
The rationale for this is we can make more efficient lookups for location
sub-trees in the planner frontend, when querying for location-specific
booking requests. This would be in the context of a booking's manager who is
only permitted to view bookings within their own location sub-tree.
=> Include `booking_location_id` in JSON payload

app/forms/booking_request_form.rb, app/views/booking_requests/step_two.html.erb, config/locales/en.yml, features/step_definitions/customer_booking_request_steps.rb, spec/forms/booking_request_form_spec.rb, spec/requests/complete_booking_request_spec.rb
This field is now required, and is a reference to the customer
accepting Pension Wise's terms and conditions.
=> Use opt_in as terms and conditions acceptance

app/assets/stylesheets/helpers/_javascript.scss, app/assets/stylesheets/vendor/_slot-picker.scss, app/views/booking_requests/step_one.html.erb
The calendar is progressively enhanced up from three standard
select boxes, so we simply fall back to these for users where
javascript is not available.
=> Improve online booking journey for users without javascript

content/after_your_appointment.md
Removed text from the digital summary document start page that states
customer will get a printed version as well.
=> Digital Summary doc start page content change

config/environments/production.rb, config/initializers/online_booking_locations.rb, lib/cached_booking_locations_api.rb
Use a read-through cache to store booking locations JSON in memory and
save a bunch of roundtrips to the API during the booking process. The
locations have a TTL of two hours by default.
For the timebeing we're configured to use the memory store cache, but
it may make more sense in future to use the redis cache or something
shared, not per-dyno.
=> Cache booking locations in memory

lib/booking_requests/api.rb
Bumps the default timeout to 10 seconds for both connect and read.
Also, since the endpoint is not considered idempotent I have disabled
retries.
If the timeouts persist, I'll make the API call asynchronously and handle it
that way. There is no overriding reason why this interaction couldn't be
backgrounded anyway, as we don't present the response to the user as the
request is always considered valid.
=> Configure HTTP connections for bookings API

app/forms/booking_feedback_form.rb, lib/feedback.rb, lib/feedback/stub_client.rb, lib/feedback/zen_desk_client.rb, spec/lib/feedback/zen_desk_client_spec.rb
Reworks the ticket creation to make them appear as though they're sent
directly from the customer. This allows us to track customer
interactions in zendesk much more efficiently.
=> Open feedback tickets from the customer

features/step_definitions/calculator_steps.rb, lib/guaranteed_income_calculator.rb, spec/features/guaranteed_income_analytics_spec.rb
There has been quite a significant change in annuity rates in
recent months. This change brings the guaranteed income
calculator inline with this.
=> Update to latest annuity market average rates

.travis.yml
This deployment configuration was created before the existence of
heroku pipelines. Our other projects use pipelines and auto-deploys so
we should use those features here too.
=> Deploy using heroku auto-deploys

app/views/layouts/_base.html.erb
In order to fix the following error: -
``And I provide my personal details                # features/step_definitions/customer_booking_request_steps.rb:62
expected `#<Pages::BookingStepTwo:0x007ff751ff1770 @addressable_url_matcher=#<SitePrism::AddressableUrlMatcher:0x007ff751ff07d0 @pattern="/locations/{id}/booking-request/step-two", @substitutions={"{id}"=>"tlifxq"}, @reverse_substitutions={"tlifxq"=>"{id}"}, @component_templates={:path=>#<Addressable::Template:0x3ffba8ff1958 PATTERN:/locations/{id}/booking-request/step-two>}>>.displayed?` to return true, got false (RSpec::Expectations::ExpectationNotMetError)
./features/support/booking_requests.rb:5:in `block in <top (required)>'
./features/support/booking_locations.rb:7:in `block in <top (required)>' …
=> Fix intermittently failing tests by disabling jQuery animations in test environment

app/forms/annuity_registration_form.rb, spec/forms/annuities_registration_form_spec.rb
This means emails can not contain spaces and
trailing spaces are removed inline with:
https://support.zendesk.com/hc/en-us/community/posts/203455266-Requester-email-is-already-used-by-another-user
=> Update email validation to stop ZenDesk errors

lib/zen_desk/client.rb, spec/lib/zen_desk/client_spec.rb
Stop errors from the ZenDesk API from being
reported to end-users. Error will be raised
to bugsnag and need to be manually handled.
=> Swallow ZenDesk errors

app/forms/annuity_registration_form.rb, spec/forms/annuities_registration_form_spec.rb
This is related to: https://app.bugsnag.com/hm-treasury-1/pension-guidance/errors/57d6a75fb3a75eb54c344639?event_id=57d6a75f4200b912001d9f75&pivot_tab=event
Validation email validation updated to avoid this error in the future.
=> Disallow '\' and '/' in email

content/guaranteed_income.md, content/when_you_die.md
The default font size was increased in the govuk elements ugprade.
This change uses the smaller version of the table font style but
still remains accessible.
=> Use smaller table style for guaranteed income facts

.travis.yml, package.json
Pension Guidance builds started failing, so this fixes it by forcing a newer version of npm
``
Done. Phantomjs binary available at /home/travis/build/guidance-guarantee-programme/pension_guidance/node_modules/phantomjs/lib/phantom/bin/phantomjs
npm ERR! EEXIST, open '/home/travis/.npm/05e49da9-is-npm-lodash-4-16-1-package-tgz.lock'
File exists: /home/travis/.npm/05e49da9-is-npm-lodash-4-16-1-package-tgz.lock
Move it away, and try again. 
npm ERR! System Linux 3.13.0-40-generic
npm ERR! command "/home/travis/.nvm/v0.10.36/bin/node" "/home/travis/.nvm/v0.10.36/bin/npm" "install"
npm ERR! cwd /home/travis/build/guidance-guarantee-programme/pension_guidance
npm ERR! node -v v0.10.36
npm ERR! npm -v 1.4.28
npm ERR! path /home/travis/.npm/05e49da9-is-npm-lodash-4-16-1-package-tgz.lock
npm ERR! …
=> Fix npm build

app/views/annuity_registration/new.html.erb, app/views/appointment_summaries/create.html.erb, app/views/appointment_summaries/new.html.erb, app/views/feedbacks/new.html.erb, content/after_your_appointment.md
/after-your-appointment
/summary-document/new
/annuity-registration
/summary-document
/feedback/new
As requested by @CassBonner
=> Add meta descriptions where missing

package.json
We should simply rely on the gem-specific phantomjs binary. Version
mismatches between the locked `1.9.8.0` and your local binary won't
cause an issue in development / test.
=> Rely on gem-specified phantomjs binary

app/assets/stylesheets/components/_options-table.scss
This change has been made in an attempt to reduce bounce rates
from this page.
We believe that adding the underline and normal link text color
will help prompt users to click through.
=> Use normal links in tax options table

Gemfile, Gemfile.lock
This bumps us to the latest phantomjs via recent compatibility updates
made in `jasmine-rails`.
=> Reliably detect / install phantomjs

config/initializers/online_booking_locations.rb
Disables Plymouth temporarily while they get their administrators together.
This reverts commit 187db6bb27c2cc49f86fcf3ac4e0fe8a4c8bb595.
=> Revert "Enable Plymouth for online bookings"

app/controllers/booking_requests_controller.rb, app/forms/booking_request_form.rb, app/views/booking_requests/step_two.html.erb, features/pages/booking_step_two.rb, features/step_definitions/customer_booking_request_steps.rb, lib/booking_requests/api_mapper.rb, spec/forms/booking_request_form_spec.rb, spec/lib/booking_requests/api_mapper_spec.rb, spec/requests/complete_booking_request_spec.rb
Makes the `date_of_birth` mandatory. The appointment type is now
inferred from the given date of birth. Both attributes are still passed
to the bookings API to maintain compatibility.
The validation works as you'd expect. When an invalid date (missing a
component) is given this does not trigger the eligibility check. When a
valid (as-in all components of the date are provided) the eligibility
check is triggered, based off the inferred appointment type.
The form looks pretty bad at the moment as I lifted it almost verbatim from
tap. @Guntrisoft - work your magic?
=> Capture `date_of_birth` when booking

app/views/booking_requests/step_two.html.erb
Some users are submitting this form twice and creating duplicate
booking requests.
=> Disable multiple submissions

app/views/locations/index.html.erb, app/views/locations/show.html.erb
Prior to this change they were a little fuzzy as they were being scaled
as `1` instead of `2` which is our maximum permitted quality on the
free plan.
=> Bump the quality of static maps

app/decorators/location_decorator.rb, app/views/locations/index.html.erb, app/views/locations/show.html.erb
* Fix the address used to generate a map on the location page
* Fix centring bug - see before/after URL below
* Zoom out images to allow better viewport of area
* Extract API key to a variable
**Map URL**
**Without centring:**
https://maps.googleapis.com/maps/api/staticmap?markers=8%20Market%20Place,%20Southwark%20Park%20Road,%20Southwark,%20London,%20SE16%203UQ&size=300x300&scale=2&zoom=15&key=AIzaSyB_H8kX3vHhOJMYIoBu3_SMnxXf-NYY3Y0
**With centring:**
https://maps.googleapis.com/maps/api/staticmap?markers=8%20Market%20Place,%20Southwark%20Park%20Road,%20Southwark,%20London,%20SE16%203UQ&center=8%20Market%20Place,%20Southwark%20Park%20Road,%20Southwark,%20London,%20SE16%203UQ&size=300x300&scale=2&zoom=15&key=AIzaSyB_H8kX3vHhOJMYIoBu3_SMnxXf-NYY3Y0
=> Improve static map images 

app/assets/stylesheets/lib/_variables.scss, app/assets/stylesheets/vendor/_slot-picker.scss, app/views/booking_requests/step_one.html.erb, bower.json, features/step_definitions/customer_booking_request_steps.rb
* Move the slot time selection to the slot being edited
* Disable slot editing - slots now need to be removed 
and readied if they are incorrect.
* Error when trying to select a 4th slot
Can be reviewed @ https://ggp-pensionwise-booking-slots.herokuapp.com/locations/183080c6-642b-4b8f-96fd-891f5cd9f9c7/booking-request/step-one
=> Improve Booking slot selection

app/views/booking_requests/step_two.html.erb
We get the occasional bad email that creeps through and while this isn't
entirely fool-proof - it does catch a number of the biggest offenders,
plus it stops the client round-tripping for a large number of cases.
=> Beefier email validation using HTML5 email fields

app/decorators/location_decorator.rb, app/decorators/location_search_result_decorator.rb, app/views/locations/index.html.erb, app/views/locations/show.html.erb, spec/decorators/location_search_result_decorator_spec.rb
This fixes a bug when the address contains '&' 
resulting in an error from Google maps
=> Escape the address before using in URL

Gemfile.lock, app/assets/stylesheets/components/govspeak/_form-download.scss, app/assets/stylesheets/components/govspeak/_info-notice.scss, app/assets/stylesheets/layout/_common_page_structure.scss
The most visible changes from this upgrade are a slight modification to the GOVUK logo, removing of the external link icon (see accessibility link in footer), and a fix for relative URLs in printing pension wise pages.
Full list of changes:
Remove generated gov.uk from relative print links
https://github.com/alphagov/govuk_template/pull/234
Fix extended footer on certain pages
https://github.com/alphagov/govuk_template/pull/177
Degrade gracefully when external JS can’t be loaded
https://github.com/alphagov/govuk_template/pull/248
Add docs for adding tabindex="-1" to fix the skiplink
https://github.com/alphagov/govuk_template/pull/250
Logo fixes
https://github.com/alphagov/govuk_template/pull/237
Remove external links styles
https://github.com/alphagov/govuk_template/pull/231
Don’t include …
=> Upgrade govuk_template to version 0.19.1

app/views/appointment_summaries/new.html.erb
- fieldsets should have a legend, but there is no need
for a legend at this part of the form so turn it
into a DIV so that it keeps the form-group class
=> Remove fieldset which does not have a legend

app/assets/javascripts/mobile-nav-toggler.js, app/assets/stylesheets/components/_nav.scss, app/views/components/_nav.html.erb
- Altered menu link to be a button which better describes
that it's going to do something interactive when clicked on
- Added aria-expanded=true/false to read out to screen reader
users that the item that it controls is collapsed, and reads
out that it's expanded when clicked on
- Added aria-hidden=true on the menu items by default, and then
turned this to true when button is clicked on, so that menu
items are only read out when the menu is expanded
- Added aria-controls for screenreaders which support it, so
a user can jump directly to the menu from the button
=> Improved accessibility of mobile version of the site navigation

app/decorators/guide_decorator.rb, app/models/guide.rb, app/repositories/guide_repository.rb, lib/front_matter_parser.rb, spec/decorators/guide_decorator_spec.rb, spec/decorators/shared_examples_for_a_guide_decorator.rb, spec/models/guide_spec.rb, spec/repositories/guide_repository_spec.rb, spec/services/create_category_navigation_spec.rb, spec/view_models/navigation_spec.rb
This change is designed to simplify the process of 
adding metadata to a guide page. 
Previously all fields needed to be declared in 
multiple places and explicitly initialised. 
This change is a small improvement to the existing
codebase with the goal of simplifying the current 
process. This change has been scope limited and is
not intended to fix all the outstanding issues.
=> Simplify the guide implementation

Gemfile.lock, config/autoprefixer.yml
- 6.4.0.1 -> 6.5.4
- See https://github.com/ai/autoprefixer-rails/blob/master/CHANGELOG.md for more details
=> Upgrade autoprefixer to latest version

app/controllers/questions_controller.rb, spec/controllers/questions_controller_spec.rb
When redirecting to a string the following URL is used:
request.protocol + request.host_with_port + options
This means `redirect_to 'pension-type-tool/question-1'` was
redirecting to:
https://staging-www.pensionwise.gov.ukpension-type-tool/question-1
Not sure why this issue did not present locally.
=> Fix redirection bug

content/pension_type_tool/question_1.md, content/pension_type_tool/question_2.md, content/pension_type_tool/question_3.md, content/pension_type_tool/question_4.md, spec/controllers/questions_controller_spec.rb, spec/features/questions_spec.rb
This is required in order for the page to redirect
correctly when no answer is provided.
=> Fix question id to use '-'

app.json
The multi buildpack has ceased to be. Heroku now supports multiple
buildpacks as first-class citizens so we should use that style of
configuration instead.
=> Modernise buildpack configuration

app/controllers/application_controller.rb, app/controllers/questions_controller.rb, app/views/layouts/_base.html.erb, config/initializers/session_store.rb
After upgrading to Rails 5.0.1 CSRF protection attempts to clear the
flash upon failure, unfortunately a bug in Rails means it doesn't guard
against us not actually loading the session middleware thus causing the
app to crash where usually CSRF failures would be silent.
We now fail with exceptions for CSRF failures so we can catch them
early on. For the bookings, where we take sensitive data we absolutely
should ensure CSRF verification happens so I have enabled this. For the
other tools this isn't such an issue.
Given the nature of the pension type tool we cannot enable CSRF
verification so this is disabled entirely.
=> Enable CSRF protection where possible

features/support/poltergeist.rb
This stops our tests loading remote assets, speeding up the tests
generally but also silencing the stupid console output from smart
survey's scripts.
=> Whitelist local assets only during JS tests

config/routes.rb
This should have gone with 5ad1497 when we stopped taking annuity
registrations.
=> Remove annuity registration routes

app/middleware/strip_session_cookie.rb, app/repositories/guide_repository.rb, config/application.rb, spec/middleware/strip_session_cookie_spec.rb
The guides were cacheable prior to 8bfd9f1 that added CSRF protection,
requiring cookies to be enabled. After 8bfd9f1 I noticed a great deal
more traffic at the origin. This will no doubt affect us over the next
few weeks as more traffic arrives due to marketing attempts.
Cloudflare will not cache content returned from the origin when the
`Set-Cookie` response header is present. To restore public caching for
the guide pages we can simply strip away cookies from the request /
response - leaving the other pages to process cookies as normal.
The middleware is loaded early on during the boot process (before Rails
has autoloaded) thus the need to explicitly require the
`GuideRepository` and its dependents.
=> Strip cookies for guide paths

app/assets/javascripts/video-player.js.es6
To allow our analytics team to see the state change of the YouTube video player
=> Add video state change to GTM dataLayer

app/repositories/guide_repository.rb, config/application.rb, config/routes.rb, spec/repositories/guide_repository_spec.rb
This generates the lists of slugs from the file name
taking into account language specific files.
Previously the `all` method required the files to be 
read in.
In addition the result of slugs has been cached on
GuideRespository object.
=> Add GuideRespository.slugs method

app/assets/stylesheets/vendor/_slot-picker.scss
=> Fix visual bug with padding around date/time confirmation

app/controllers/feedbacks_controller.rb, spec/features/feedback_spec.rb
This was failing to work as the cookies are striped
from the page to enable caching. This change requires
CSRF protection from the feedback submission form.
=> Allow feedback to be left on the pension type tool

app/assets/stylesheets/helpers/_visually-hidden.scss
- visually-hidden is the standard class to use for
govuk pages to hide text from visual users, but
allow the text to be read by screen readers
- Adding visibility: hidden to visually-hidden class
results in Jaws on Windows not reading the content
=> Remove visually-hidden class override from project

app/views/appointment_summaries/create.html.erb
- avoid duplication of element IDs
- makes page HTML valid
=> Namespacing IDs for form elements

app/controllers/marketing_controller.rb
Was accidentally left over from a previous iteration.
=> Remove redundant action in marketing controller

Gemfile, Gemfile.lock, app/views/appointment_summaries/new.html.erb, features/accessibility.feature, features/cassettes/Accessibility_of_pages/Location_page_is_accessible.yml, features/step_definitions/accessibility_steps.rb, features/step_definitions/appointment_summary_steps.rb, features/step_definitions/customer_booking_request_steps.rb, features/step_definitions/location_steps.rb, features/support/env.rb
Using axe-matchers gem to integrate accessibility tests into a set of new cucumber features.
The tests which are run against the pages are listed here:
https://github.com/dequelabs/axe-core/blob/master/doc/rule-descriptions.md
Altered steps which select radio buttons on appointment summary form page to ensure they work with features with/without Javascript
=> Adding in aXe accessibility testing

app/lib/booking_requests/api_mapper.rb, spec/lib/booking_requests/api_mapper_spec.rb
To facilitate displaying when the customer specified they were unsure
whether their pension was DC, we now pass their selection through to
the bookings API per the requirements for displaying in planner.
=> Pass 'not sure' through to bookings API

app/views/marketing/landing.html.erb, config/routes.rb, public/robots.txt
The page is identical to the existing 'facebook landing' page,
except this one is to be used for various other digital marketing
and no phone number to promote online booking.
=> Alternative landing page available at `/landing`

app/controllers/locations_controller.rb, app/views/components/_error_postcode.html.erb, app/views/components/_locations_search.html.erb, app/views/locations/empty_postcode.html.erb, app/views/locations/invalid_postcode.html.erb, content/book_face_to_face.md, features/find_nearest_face-to-face_appointment_locations.feature, features/pages/locations_page.rb, features/step_definitions/location_steps.rb, spec/controllers/locations_controller_spec.rb
If a user does not enter a postcode on face to face location
search then we show the location search again but include
a suitable error message to inform the user what they need
to do
=> Show error message when customer does not enter a postcode

app/views/booking_requests/completed.html.erb, app/views/booking_requests/step_one.html.erb
**Step One**
**Confirmation**
Customers have been complaining about not getting their
chosen date/times, this improves the copy and makes it
more prominent
=> Improve face-to-face appointment availability copy

Gemfile, Gemfile.lock
Includes:
- Fix address location on ineligible letters (from 4.4.4)
- Updates to ineligible letter content (from 4.4.5)
- New phone number for Future Pension (from 4.4.5)
=> Bump output_templates to version 4.4.5

app/views/application/_ineligible.html.erb, app/views/booking_requests/ineligible.html.erb, app/views/telephone_appointments/ineligible.html.erb
Improves the language (eg use of 'pension' singular sounded a bit odd)
and to add links to the pension type tool to hopefully help users
understand their pension type and therefore the reason they're
ineligible.
=> Content changes to ineligible page

app/views/telephone_appointments/confirmation.html.erb, features/step_definitions/telephone_booking_request_steps.rb
User research found that users were finding the page
ambiguous in terms of what they would receive in the
confirmation email and they would like to know the
details of their appointment in case the email
didn't reach them.
Switched to two thirds layout which is the same as
face to face booking request confirmation page
=> Update copy on telephone booking confirmation page

app/views/home/show.html.erb, app/views/layouts/_two_column.erb
Analytics team have requested an easier way to target the book
appointment link at the top of the site.
Added a different ID for the homepage link to distingish between
homepage and other pages of the site
=> Add unique id for book appointment link

app/views/telephone_appointments/_step_1.html.erb, app/views/telephone_appointments/_step_2.html.erb, app/views/telephone_appointments/_step_3.html.erb, app/views/telephone_appointments/confirmation.html.erb, app/views/telephone_appointments/ineligible.html.erb, app/views/telephone_appointments/new.html.erb
This will help the analytics team work out which page is being
served, for the purpose of seeing how far customers are getting in the
booking process.
At present both the time selection (non-js) and customer details form
are both being served at the URL '/telephone_appointments'.
Changing the page title helps the analytics team separate out
those different page view types.
=> Adding per page titles for each step of the telephone booking process

app/controllers/questions_controller.rb, app/repositories/guide_repository.rb, app/views/layouts/guides.html.erb, app/views/questions/_yes_no_dont_know_question.html.erb, config/application.rb, config/locales/en.yml, spec/features/questions_spec.rb
When the customer forgets to supply an answer on any of the pension type
tool questions we currently just redirect back, guarding them from
proceeding but without any explanatory text.
This change adds a flash warning message above the heading asking the
customer to complete and submit their answer correctly.
=> Warn when a question is unanswered

config/routes.rb, features/pages/ineligible_for_appointment.rb, features/pages/new_telephone_appointment.rb
We favour dashes over underscores for customer-facing URIs.
=> Dasherise the TAP journey URLs

app/decorators/guide_decorator.rb, app/views/home/show.html.erb, app/views/layouts/_two_column.erb, content/adjustable_income.md, content/guaranteed_income.md, content/leave_pot_untouched.md, content/mix_options.md, content/take_cash_in_chunks.md, content/take_whole_pot.md
Analytics team have requested we remove the ids previously added
to book appointment links and add unique tracking URLs which
will help them work out which book appointment link has been
clicked on a page.
=> Add unique URLs for book appointment links on home/guide pages

content/adjustable_income.md, content/guaranteed_income.md, content/leave_pot_untouched.md, content/mix_options.md, content/pension_statements.md, content/take_cash_in_chunks.md, content/take_whole_pot.md
Added link to the pension type tool to all options pages and pension statements page to potentially increase click-through rate and conversion. Moved book appointment link from under next steps section of options pages to within body copy of pages to provide greater visibility.
=> Promotion of Pension Tool / Moving Book appointment links

Gemfile.lock, app/forms/booking_request_form.rb, features/customer_booking_request.feature, features/fixtures/locations_with_online_booking.json, features/step_definitions/customer_booking_request_steps.rb
We need to display per-location slots for face-to-face bookings due to
the upcoming location closures. These changes ensure the calendar is
bound to the chosen location's slots, not its booking location as
before.
=> Accommodate per-location slots for face-to-face

app/models/guide.rb, app/views/guides/show.html.erb, app/views/layouts/_base.html.erb, content/cymraeg.md, spec/models/guide_spec.rb
This aids speech synthesis tools to determine what pronunciations to use,
and translation tools to determine what rules to use.
=> Specifying that text is in welsh where appropriate

public/robots.txt
As we are rolling out booking a telephone appointment online
as a private beta, we don't want the form to be searchable
just yet.
=> Disallow spidering of /telephone-appointments/ URLs

public/robots.txt
There is no reason why we shouldn't allow search engines to spider
the starting/introduction page of the pension type tool and the
page for the first question.
Anything further into the tool itself should be disallowed as it
requires the first question to be answered first.
=> Be more exact on which pages to disallow of the pension type tool

content/pension_type_tool/might_defined_contribution.md
Corrected call out copy - didn't make sense in context of the answer.
=> Correct call out copy

app/views/telephone_appointments/confirmation.html.erb
After the latest round of the user research lab we found that we need
to place the call centre number on the online telephone booking
confirmation page in case the customer needs to get in touch regarding
the details of the appointment.
=> Include TPAS phone number on online telephone booking confirmation page

Gemfile, Gemfile.lock, config/environments/production.rb
Using the redis store instead of the memory store means the cache
survives app restarts and is shared across however many web processes
we are using. This is favourable to each web process maintaining its
own in-memory cache.
=> Cache booking locations with redis store

app/views/telephone_appointments/_step_3.html.erb
Made label text bold to match GOV.UK form elements and added hint text on pension types as response to user feedback.
=> Update customer details form for phone booking

app/views/booking_requests/step_two.html.erb
Bold text labels to match GOV.UK form elements and new hint text based on user research feedback.
=> Update customer details form in F2F booking journey

content/appointments.md, content/pension_type_tool/defined_contribution.md, content/pension_type_tool/might_defined_contribution.md, content/pension_type_tool/most_cases_defined_contribution.md
Given more prominence to pension tool on /appointments page to help users 'self-diagnose' before booking. Added green start buttons to pension tool answer pages to help make booking an appointment stand out more.
=> Improvements to pension tool journey

app/assets/stylesheets/vendor/_slot-picker.scss
In order to deal with the fact that some locations are closing,
the calendar is starting to show less than a month's worth of
days, which has caused a visual issue with the calendar design.
This change introduces a max-height instead of a fixed height
so the calendar can get smaller
**Before**
**After**
=> Alter the Calendar for F2F to have a max-height instead of height

content/adjustable_income.md, content/take_cash_in_chunks.md, content/work_out_income.md
Changes to the money purchase annual allowance figure. New figure of £4,000 replacing £10,000 from 6 April. Policy have requested we inform users about this in advance.
=> Updated allowance figures

app/assets/stylesheets/components/_footer-categories.scss, app/views/appointment_summaries/create.html.erb, app/views/components/_footer_categories.html.erb, app/views/guides/_option.html.erb
The headers in the footer are better placed to be `H2`s as a descendant of the main header of the page (`H1`).
As `H3`s they ended up being a sub header of a random section of content which they were completely unrelated to.
Alter guide sidebar to be an `<aside>` element to aid screen readers.
Removes H2 header from the guider page right column as it is a repeat of the H1 of the page, and adds confusion.
**Example Document outline after change**
=> Alter headers in footer of site to H2s / Guider sidebar to <aside>

app/assets/stylesheets/components/govspeak/_steps.scss
This ensures the text is vertical centered correctly
=> Correct steps line-height to match height of circle

config/routes.rb
We've accidentally used the wrong link in GTM so this redirect covers
that until we get it resolved over there.
=> Temporarily redirect due to broken GTM link

app/controllers/telephone_appointments_controller.rb
The confirmation page was relying on flash parameters being set by the
referring action, when customers refreshed the page their session would
generally be expired and an error would occur.
Passing these values along with the query string works around the issue.
=> Survive refreshes using query string parameters

features/step_definitions/customer_booking_request_steps.rb
We need to explicitly wait for the slots to be bound here before
asserting on their presence.
=> Fix a timing issue in the booking feature

app/controllers/telephone_appointments_controller.rb
Prior to this change we were overzealously checking eligibility
regardless whether the fields needed to determine these facts were
supplied by the customer.
This simple change just checks the values are valid before applying the
eligibility rules.
=> Check fields are valid before ineligible

app/controllers/booking_requests_controller.rb, app/forms/booking_request_form.rb, features/customer_booking_request.feature, features/step_definitions/customer_booking_request_steps.rb, spec/forms/booking_request_form_spec.rb, spec/lib/booking_requests/api_mapper_spec.rb
Prior to this change we were overzealously checking eligibility
regardless whether the fields needed to determine these facts were
supplied by the customer.
This simple change just checks the values are valid before applying the
eligibility rules.
=> Check F2F fields are valid before ineligible

Gemfile.lock, app/controllers/locations_cache_controller.rb, config/routes.rb, spec/requests/locations_cache_sweeper_api_spec.rb
We need a way of remotely triggering a cache flush when booking
locations change structurely. This change adds an API endpoint, with
simple token based authentication. We are not using SSO here since this
application is not backed by a persistent store - a requirement for
GDS-SSO and signon integration.
A request issued to `DELETE /locations_cache` with the correct
authorisation token will sweep the cached locations and leave
non-prefixed (anything other than our locations) entries as-is.
=> Expose an API for clearing booking locations

app/views/components/_page_nav.html.erb
This navigation was aggressively cacheable and was taking on average
around 40% of the total time to render the page. Once rendered it is
completely static and changes very, very rarely.
This change caches the fragment for an arbitrary two hours.
From the results below (in development mode on my laptop) you can see
the response time drop from ~500ms to ~300ms.
Before:
```
Started GET "/" for ::1 at 2017-03-17 19:57:28 +0000
Processing by HomeController#show as HTML
Rendering home/show.html.erb within layouts/home
Rendered home/show.html.erb within layouts/home (1.6ms)
Rendered components/_logo_link.html.erb (1.2ms)
Rendered feedbacks/_form.html.erb (3.6ms)
Rendered feedbacks/_feedback_form.html.erb (11.7ms)
Rendered calculators/_form_input_currency.html.erb (1.3ms)
Rendered …
```
=> Cache page navigation elements

Gemfile.lock
This addresses the bug with prefixing in `booking_locations`.
=> Ensure locations are cached correctly

Gemfile, Gemfile.lock, app/controllers/application_controller.rb, app/controllers/locations_cache_controller.rb, app/controllers/lograge_filterer.rb, config/environments/production.rb
Reduce logging into a single line format to avoid interleaving of
requests.
=> Format single line output with lograge

config/routes.rb, content/book_phone.md
After a successful trial of adding the online booking button to the `book-phone` page, this will add the button permanently to the page - thus officially launching online telephone booking 🎉
=> Add book online button to phone page

app/decorators/cached_guide_decorator.rb, spec/decorators/cached_guide_decorator_spec.rb
Up to now content items were being cached indefinitely. This was not a
problem when we were configured to use the memory store that wouldn't
survive application restarts but is now we use an out-of-process cache
store via Redis. This change ensures we respect the TTL on content
items.
=> Ensure content is cached with a TTL

content/pension_type_tool/defined_contribution.md, content/pension_type_tool/might_defined_contribution.md, content/pension_type_tool/most_cases_defined_benefit.md, content/pension_type_tool/most_cases_defined_contribution.md
In preparation of adding a smart survey to the answer pages
of the pension type tool, Product have asked us to remove
the feedback links as it will confuse users.
=> Remove feedback link from pension type tool answer pages

app/assets/stylesheets/experiments/components/_quick-links.scss, app/assets/stylesheets/experiments/layout/_homepage.scss, app/assets/stylesheets/experiments/lib/_variables.scss, app/controllers/home_controller.rb, app/views/home/experiment.html.erb, app/views/layouts/_base.html.erb, app/views/layouts/experiments/home.html.erb, config/routes.rb
This brings back the /home-alternative URL and provides
an alternative homepage to use in a A/B test.
=> Prototyping a new version of the Pension Wise homepage

app/domain/breadcrumb.rb
Content team have requested this to avoid duplication of the
word free and mention phone instead of telephone as per
the page title
=> Update breadcrumb name for telephone appointments page

app/views/locations/index.html.erb
Feedback from DWP content team suggested the wording could
be improved.
=> Improve wording on face to face search results page

app/views/booking_requests/completed.html.erb, app/views/booking_requests/ineligible.html.erb, app/views/telephone_appointments/_step_2.html.erb, app/views/telephone_appointments/_step_3.html.erb, app/views/telephone_appointments/confirmation.html.erb, app/views/telephone_appointments/ineligible.html.erb
Some titles were missing on pages on the booking journey.
They were also inconsistent between telephone and face to face
so this addresses that too.
=> Standardise page titles across booking journeys

app/views/telephone_appointments/_step_3.html.erb, content/book_face_to_face.md, content/book_phone.md
As part of the new agreement the opening times for the call centre to
book Pension Wise appointment is now 8am - 8pm Monday to Friday.
The new times will need to be reflected on the website where shown.
=> Call centre opening time changed

app/assets/stylesheets/components/_govuk-box-highlight.scss, app/views/booking_requests/completed.html.erb, app/views/telephone_appointments/confirmation.html.erb
DWP feedback recommended that we changed our confirmation pages
to be inline with govuk standards here:
https://www.gov.uk/service-manual/design/confirmation-pages
=> Make confirmation pages for both booking journeys consistent with govuk

app/assets/stylesheets/components/slot-picker/_slot-picker-times.scss, app/controllers/telephone_appointments_controller.rb, app/views/telephone_appointments/_hidden_fields.html.erb, app/views/telephone_appointments/_step_2.html.erb, app/views/telephone_appointments/_times.html.erb, app/views/telephone_appointments/_times_js.html.erb, app/views/telephone_appointments/new.html.erb, features/pages/new_telephone_appointment.rb, features/step_definitions/telephone_booking_request_steps.rb
After a user selected a time we were moving them on automatically
to the customer form page.
Feedback from DWP content team suggested that the standard
gov.uk way is to let a user make a choice and then decide to
continue to the next step by clicking a 'continue' button
=> Adding a continue button to the telephone appointment form

app/controllers/questions_controller.rb, app/forms/feedback_form.rb, app/views/appointment_summaries/new.html.erb, app/views/components/_error_postcode.html.erb, app/views/components/_locations_search.html.erb, app/views/feedbacks/_form.html.erb, app/views/layouts/guides.html.erb, config/locales/en.yml
This makes the feedback form, the pension type tool, appointment summary
and location search forms consistent with the wording that has been
introduced on the booking journey forms
=> Make error messages on the site consistent with booking journey errors

app/views/calculators/_error_summary.html.erb, app/views/calculators/_form_input_currency.html.erb, app/views/calculators/_form_input_number.html.erb, app/views/calculators/adjustable_income/_form.html.erb, app/views/calculators/guaranteed_income/_form.html.erb, app/views/calculators/leave_pot_untouched/_form.html.erb, app/views/calculators/take_cash_in_chunks/_form.html.erb, app/views/calculators/take_whole_pot/_form.html.erb, config/locales/calculators.en.yml, config/locales/calculators/adjustable_income.en.yml, config/locales/calculators/guaranteed_income.en.yml, config/locales/calculators/leave_pot_untouched.en.yml, config/locales/calculators/take_cash_in_chunks.en.yml, config/locales/calculators/take_whole_pot.en.yml
This is to ensure that we have a consistent set of error messages
across the site
=> Updating calculator error msgs to be inline with other error msgs

features/support/poltergeist.rb, spec/spec_helper.rb
We're seeing builds fail intermittently in CI due to the initial wait
time for asset compilation. This happens only once per build but causes
the whole build to fail. Setting this to a large maximum (60 seconds by
default) should address the build failures and need for rebuilds.
=> Increase phantomjs / poltergeist timeout

config/locales/calculators/guaranteed_income.en.yml
After feedback from the content team it has been decided to
amend the error message for users who enter an age younger
than 55 or older then 75.
=> Amend error messages for guaranteed income calculator

config/newrelic.yml
We are not using the New Relic browser features, so
best turn it off to reduce the frontend HTTP requests
=> Disable New Relic Browser

content/pension_type_tool.md
Service manual for gov.uk states that a start button should have a
chevron and a bigger looking button than a standard one.
https://www.gov.uk/service-manual/design/start-pages
=> Ensure that pension type tool start button looks like govuk start button

app/views/home/experiment.html.erb, app/views/home/show.html.erb
Analytics team have recommended we add the 'page hiding script'
to our A/B testing pages (homepage) to avoid a page flicker
when the page loads.
More details:
http://www.lunametrics.com/blog/2017/03/02/install-google-optimize/#3-how-to-install-the-optimize-snippet
=> Prevent flicker effect when A/B test is run

app/assets/stylesheets/components/summary-document.scss
This fixes some rendering issues with the text of the summary
document generated by the view your appointment summary tool.
=> Improve display of summary document information on website

app/assets/stylesheets/components/_locations-a-z.scss, app/controllers/locations_controller.rb, app/views/locations/a_to_z.html.erb, content/book_face_to_face.md, spec/controllers/locations_controller_spec.rb
In order to make our location pages available to search engines
this creates an A-Z list of locations which is accessed by a link
under the location search box
=> Altering /locations to display an A-Z of all locations

app/forms/booking_request_form.rb, app/models/telephone_appointment.rb, spec/forms/booking_request_form_spec.rb, spec/models/telephone_appointment_spec.rb
This adds very primitive validation just to ensure we get something
approaching a correct telephone number.
=> Validate structure of phone numbers

app/views/locations/index.html.erb, app/views/locations/show.html.erb
Customers have been geting confused about the wording of the
booking hours on the location pages. They were thinking that the
hours specified meant when the location was available for an
appointment rather than when the phone lines were open.
This alters the wording slightly to help reduce this confusion.
=> Alter wording on location page to better clarify phone booking hours

app/controllers/booking_requests_controller.rb, app/controllers/telephone_appointments_controller.rb, app/forms/booking_request_form.rb, app/lib/booking_requests/api_mapper.rb, app/models/telephone_appointment.rb, app/views/booking_requests/step_two.html.erb, app/views/telephone_appointments/_hidden_fields.html.erb, app/views/telephone_appointments/_step_3.html.erb, config/locales/en.yml, features/pages/booking_step_two.rb, features/pages/new_telephone_appointment.rb, features/step_definitions/customer_booking_request_steps.rb, features/step_definitions/telephone_booking_request_steps.rb, spec/cassettes/BookingRequests_Api/_create/when_the_request_is_successful/returns_true.yml, spec/forms/booking_request_form_spec.rb, spec/lib/booking_requests/api_mapper_spec.rb, spec/lib/telephone_appointments_api_spec.rb, spec/models/telephone_appointment_spec.rb, spec/requests/complete_booking_request_spec.rb
This removes the terms and conditions question from both face to face and telephone appointment booking journeys.
This has come from a DWP content review.
=> Remove terms and conditions questions

Gemfile, Gemfile.lock, app/assets/javascripts/application.js, app/assets/javascripts/components/EmailValidation.es6, app/assets/stylesheets/components/_ajax-loader.scss, app/assets/stylesheets/components/_button-link.scss, app/assets/stylesheets/components/_email-outer.scss, app/assets/stylesheets/components/_email-suggestion.scss, app/helpers/application_helper.rb, app/views/booking_requests/step_two.html.erb, app/views/feedbacks/_form.html.erb, app/views/telephone_appointments/_step_3.html.erb, app/views/telephone_appointments/_times_js.html.erb, features/customer_booking_request.feature, features/pages/booking_step_two.rb, features/pages/new_telephone_appointment.rb, features/step_definitions/customer_booking_request_steps.rb, features/step_definitions/telephone_booking_request_steps.rb, features/support/mock_mailgun.rb, features/support/poltergeist.rb, features/telephone_booking_request.feature
Using mailgun's email validation API to check email addresses
inputted into booking forms.
Suggests alternative email addresses if it detects the
domain is maybe a typo.
Added to both booking journeys and feedback form.
=> Adding email validation to email fields

app/views/home/show.html.erb
Now that we have ended the A/B test for the homepage we can
now remove this 'page hiding script'
Originally added in:
https://github.com/guidance-guarantee-programme/pension_guidance/commit/3b8c633b12194fc6184082b8841cf68484d53045
=> Remove google experiments code which prevents page flicker

app/views/home/show.html.erb
Updated bullet sentence style so that when a colon introduces a list, the first word after the colon isn't capitalised.
=> Update homepage cap style

app/assets/javascripts/application.js, app/assets/javascripts/components/Navigation.es6, app/views/components/_page_nav.html.erb, spec/javascripts/navigationSpec.js
An error was being generated from the navigation module on the marketing page.
This was down to the navigation menu not appearing on the marketing page.
This ensures that the navigation module is only executed when the
navigation is present on a page.
=> Fix JS error that occurs on marketing page

features/support/locale.rb, spec/spec_helper.rb
Locale state was leaking between specs and causing failures depending
on order. To address this we can simply 'reset' the locale back to
English after each test run in both RSpec and Cucumber.
=> Reset the current locale to `en` after each test

app/views/guides/show.html.erb, app/views/home/show.html.erb, app/views/layouts/_base.html.erb
Previous PR for this only addressed guides, but needed to be applied to any and all pages.
The logic that makes the decision has been moved into the the base layout, negating the need for the `canonical_path` content_for area.
=> Use English url for ANY page’s canonical tag when not yet translated

app/views/locations/show.html.erb
**Note: These changes need to get merged after scheduling for F2F appointments is live**
Now that location pages are surfaced in Google search results
we need to add some text about appointments being for
people over 50 with a DC pot.
This also simplifies the text on the page generally and
brings the h2 headers back to their standard size.
=> Add DC pot information on location pages

Gemfile.lock, app/forms/booking_request_form.rb, app/lib/booking_requests.rb, app/lib/booking_requests/api.rb, app/lib/booking_requests/slot.rb, app/lib/booking_requests/stub_api.rb, features/accessibility.feature, features/customer_booking_request.feature, features/step_definitions/customer_booking_request_steps.rb, spec/cassettes/BookingRequests_Api/_slots/returns_slots_for_the_given_location.yml, spec/lib/booking_requests/api_spec.rb, spec/lib/booking_requests/booking_requests_spec.rb
Bookable slots for face-to-face appointments are no longer the domain of
our location register and have been replaced by real schedules/availability
from the newly introduced planner API.
=> Retrieve bookable slots from planner API

app/views/layouts/_base.html.erb
This was causing a significant increase in time taken to render the
base layout since calculating topics/categories is quite expensive to
compute. Caching these fragments is a quick-win.
=> Cache footer categories

public/robots.txt
This puts a wildcard language directory at the start of URLs
in the robots.txt file.
It also removes some URLs from the robots.txt which are no
longer valid, and adds in /*/booking-request/ to avoid
step one of the f2f booking process from being indexed.
It was felt that allowing customers to go straight to the
booking form without explaining who is suitable for a
Pension Wise appointment might increase the chances of
getting invalid appointments.
=> Update robots.txt to take into account welsh language URLs

app/controllers/booking_requests_controller.rb, app/forms/booking_request_form.rb, app/views/booking_requests/no_availability.html.erb, features/customer_booking_request.feature, features/pages/booking_step_one.rb, features/step_definitions/customer_booking_request_steps.rb, features/support/booking_requests.rb
If a location has no availability then this shows a message
for the customer to call the location instead of showing
an empty calendar.
=> Alter booking form step one to show no availibility message

app/assets/javascripts/application.js, app/assets/javascripts/components/CharacterLimit.es6, app/controllers/booking_requests_controller.rb, app/forms/booking_request_form.rb, app/lib/booking_requests/api_mapper.rb, app/views/booking_requests/step_two.html.erb, spec/forms/booking_request_form_spec.rb, spec/lib/booking_requests/api_mapper_spec.rb
**This PR needs to be merge after this one https://github.com/guidance-guarantee-programme/planner/pull/169**
This introduces an additional information text field which allows customers to specify an additional amount of information about their booking request e.g. times they aren't available during
a AM/PM slot.
It also introduces a character limit module in JS which
a) Limits input to the textbox to 160 chars on older browsers which don't support the maxlength attribute on a <textarea>
b) Displays a character remaining count underneath the textarea
c) Makes use of the aria-live and aria-atomic attributes when the user is getting low on characters left, so screen reader users are aware that they are starting to hit the character limit.
=> Adding an additional info field to F2F booking form

app/views/locations/index.html.erb
The `=` was missing thus the `link_to` was not being evaluated. I've
also changed the path to go directly to the guide for phone bookings,
to be consistent with our usage elsewhere.
=> Correct issue with ERB response

app/views/locations/show.html.erb
As all location addresses have been updated fully we no longer require
the location title and Citizens Advice reference as this does not apply
to a number of locations. The 1st line of the address contains the
information whether its a Age Uk or Citizens advice location.
=> Removing reference to Citizens Advice from all location pages

Gemfile, Gemfile.lock
Bumps `output-templates` for the latest changes based on recent guider
feedback.
=> Bump `output-templates`

config/application.rb
Previously the home page was attempting to write a cookie thus causing
a cache MISS at the edge. Stripping cookies on the home page response
ensures we can cache this content and improve the experience for our
customers.
=> Strip cookies to cache home pages

Gemfile, Gemfile.lock
Updating version of output-templates based on typo fixes to the summary
document
=> Bumping output-templates version

app/controllers/booking_requests_controller.rb, app/forms/booking_request_form.rb, app/lib/locations/location.rb, app/views/booking_requests/step_one.html.erb, app/views/locations/index.html.erb, app/views/locations/show.html.erb, config/initializers/online_booking_requests.rb, features/accessibility.feature, features/customer_booking_request.feature, features/fixtures/locations.json, features/step_definitions/location_steps.rb, features/support/booking_requests.rb, spec/lib/booking_requests/booking_requests_spec.rb, spec/support/helpers/with_stub_booking_requests_api.rb
Some ground work needed before making the very simple addition of view logic to perform the task at hand, but handily was able to pull over a few of the commits from my parked [limited availability PR](https://github.com/guidance-guarantee-programme/pension_guidance/pull/946).
=> Hide 'Book online' button when a location has no availability

public/robots.txt
We've seen bots hit this page for hidden locations so let's avoid that
by using the right wildcards.
=> Don't crawl the f2f bookings start page

app/forms/booking_request_form.rb, app/lib/booking_requests/api_mapper.rb, app/views/booking_requests/step_one.html.erb, app/views/booking_requests/step_two.html.erb, features/customer_booking_request.feature, spec/forms/booking_request_form_spec.rb, spec/lib/booking_requests/api_mapper_spec.rb
Previously we required three choices at all times. We now need just one
slot chosen for the customer to proceed but still recommend up to 3
choices.
Needs coordination with guidance-guarantee-programme/planner#175.
=> Permit between one and three face-to-face slots

app/views/home/show.html.erb
Remove 'Understand your pension statement'.
Add at the top of the list 'What you can do with you pot'
=> Updates to “Popular on Pension Wise” links on homepage

Gemfile, Gemfile.lock, app/lib/locations/reader.rb, config/initializers/redis_pool.rb, spec/lib/locations/reader_spec.rb
Previously Redis connections were unbounded by the location reader.
This change ensures they are monentarily checked out from a bounded
connection pool, so that during times of increased load we are not
exhausting all available Redis connections. This was particularly
evident while the location pages are crawled by various bots.
=> Pool Redis connections for locations

app/controllers/home_controller.rb, app/views/home/show.html.erb, app/views/marketing/index.html.erb, config/locales/cy.yml, config/locales/en.yml
Move content into locale files, add translations for welsh version and override `content_lang_matches_locale?` to suppress the notice about the page being untranslated.
Edit: doh, forgot I took a screenshot...
=> Translate home page into welsh

app/assets/stylesheets/components/govspeak/_header-logo.scss
Checked back to the initial release of the localisation and this has been an issue since the start.
Made the `z-index` of the header 1, `position: relative` required as z-index only has an effect on "positioned" elements.
Tab sequence still the same as before so looks like no accessibility side effects.
=> Use `z-index` to bring logo up above the language toggle container

app/controllers/telephone_appointments_controller.rb, spec/features/telephone_appointment_spec.rb
When customers return to an old browser session their device may refresh
the confirmation page without the requisite parameters. We are seeing
this occur a few times weekly in our error tracker. Rather than display
an error we should simply return them to the homepage.
I've only checked the presence of the `booking_reference` parameter
since one will not exist without the other when refreshing.
=> Don't error when refreshing a confirmation

content/pension_type_tool/defined_contribution.cy.md, content/pension_type_tool/defined_contribution.en.md, content/pension_type_tool/might_defined_contribution.cy.md, content/pension_type_tool/might_defined_contribution.en.md, content/pension_type_tool/most_cases_defined_contribution.cy.md, content/pension_type_tool/most_cases_defined_contribution.en.md
A link in the pension type tool that previously linked back to the start of the tool, now linking to the self serve journey.
=> Update link from pension type tool to self serve journey

app/forms/booking_request_form.rb, app/lib/locations/location.rb, spec/cassettes/Alternative_locations/when_there_are_less_than_three_slots_available/and_nearby_alternatives.yml, spec/features/alternative_locations_spec.rb, spec/fixtures/locations_with_alternates.json
When suggesting alternate locations we should exclude those that are
not available for online bookings.
=> Ensure correct locations are suggested

config/locales/cy.yml, config/locales/en.yml, content/for_employers.cy.md, content/for_employers.en.md
Slug is `/en/for-employers` (and `/cy/for-employers`).
=> Add 'Pension Wise for employers' page

app/views/components/_breadcrumbs.html.erb, config/locales/cy.yml, config/locales/en.yml
I noticed this wasn't translated before so had a crack.
=> Translate the home breadcrumb

app/assets/javascripts/click-tracker.js, app/views/pension_summaries/summary.html.erb
Now that we have worked out how to track these clicks via GTM, revert this initial attempt at doing so.
=> Revert "Track printing and downloading of pension summaries"

app/views/booking_requests/step_one.html.erb
We can target via css with GA but there aren't really any decent structural classes that we can leverage in order to reliably target these links, so adding some dedicated classes directly to the links.
Following the BEM pattern, went with a `ga-` prefix.
=> Add a class to identify alternate location links for the purpose of GA

app/lib/locations/location.rb, spec/lib/locations/location_spec.rb
Locations that are not enabled for online booking should never report
limited availability.
=> Limited availability only for online booking

app/forms/feedback_form.rb, spec/forms/feedback_form_spec.rb
We were permitting incorrectly formatted email addresses for feedback
and when these get through they're refused by ZenDesk resulting in an
error message to the customer. This change ensures we validate emails
more rigorously.
=> Validate feedback emails more robustly

app/controllers/booking_requests_controller.rb, app/controllers/telephone_appointments_controller.rb, app/forms/booking_request_form.rb, app/lib/booking_requests/api_mapper.rb, app/models/telephone_appointment.rb, app/views/booking_requests/step_two.html.erb, app/views/telephone_appointments/_hidden_fields.html.erb, app/views/telephone_appointments/_step_3.html.erb, config/locales/en.yml, features/pages/booking_step_two.rb, features/pages/new_telephone_appointment.rb, features/step_definitions/customer_booking_request_steps.rb, features/step_definitions/telephone_booking_request_steps.rb, spec/cassettes/BookingRequests_Api/_create/when_the_request_is_successful/returns_true.yml, spec/forms/booking_request_form_spec.rb, spec/lib/booking_requests/api_mapper_spec.rb, spec/lib/telephone_appointments_api_spec.rb, spec/models/telephone_appointment_spec.rb, spec/requests/complete_booking_request_spec.rb
This ensures the customer has explicitly accepted T&C during both the
face-to-face and telephone customer booking journeys.
=> Reinstate explicit T&C acceptance

.travis.yml, Gemfile, Gemfile.lock, features/support/poltergeist.rb
This is safe now they've sorted out their CDN. This is also faster to
use, I suspect this is something to do with how `phantomjs-binaries`
wraps the actual binary in Ruby.
=> Use `phantomjs` instead of the binaries package

app/controllers/lograge_filterer.rb, config/application.rb, config/environments/production.rb
Ensures that the correct remote IP is inferred.
=> Filter away cloudflare trusted proxies

Gemfile.lock, app/forms/booking_request_form.rb
Allows administrators to provide overridden numbers for parent/child
locations.
=> Use canonical online booking twilio number

app/controllers/booking_requests_controller.rb, app/forms/booking_request_form.rb, app/lib/booking_requests/api_mapper.rb, app/lib/where_you_heard.rb, app/views/booking_requests/step_two.html.erb, config/locales/cy.yml, config/locales/en.yml, features/pages/booking_step_two.rb, features/step_definitions/customer_booking_request_steps.rb, spec/forms/booking_request_form_spec.rb, spec/lib/booking_requests/api_mapper_spec.rb, spec/requests/complete_booking_request_spec.rb
This is during the face-to-face journey. The customer can now specify
where they first heard of Pension Wise. This option is currently
mandatory.
=> Customers can specify where they heard of us

app/models/tesco/booking.rb, spec/models/tesco/booking_spec.rb
This ensures that customers turning 50 by the time of their appointment
are eligible and thus can place a booking.
=> Calculate age at date of appointment

app/views/locations/_location.html.erb, app/views/locations/index.html.erb, app/views/locations/show.html.erb, features/step_definitions/location_steps.rb, features/view_face-to-face_appointment_location_details.feature
When the location is enabled for online bookings and the location has
no availability the customer was always presented the call centre
number. If they called the number they would be told the location has
no availability and they would reach a dead end. This change ensures
they are made aware early on when the location has no appointment
availability.
=> Don't show phone number with no availability

app/views/locations/_location.html.erb
This was hidden when the location was enabled for online booking and
had availability.
=> Ensure phone is displayed

app/views/booking_requests/completed.html.erb
Lets the customer know not to expect a response until the new year when
placing a booking.
=> Include temporary new year confirmation

app/views/booking_requests/completed.html.erb
This no longer applies after the new year break.
=> Revert "Include temporary new year confirmation"

app/models/complaint.rb, config/initializers/filter_parameter_logging.rb, spec/models/complaint_spec.rb
Ensures zendesk does not raise an error when the ticket is submitted.
=> Default requester email when not provided

app/controllers/feedbacks_controller.rb, content/tesco.cy.md, content/tesco.en.md, spec/features/feedback_spec.rb
Ensures customers can send feedback or questions when no locations are
currently active.
=> Add link to feedback in Tesco landing page

app/views/booking_requests/step_one.html.erb
These were causing confusion and have been reported via zendesk on
multiple occasions.
=> Clarify messages for slot picker

app/controllers/lograge_filterer.rb, config/environments/production.rb
This helps with GDPR compliance plus we don't use this data anyway so
it's redundant.
=> Do not log customer IP addresses

app/views/pension_summaries/summary.html.erb
Not looking for a merge here - more a steer.
Prior to this - the sidebar on /en/explore-your-options/summary disappears in the mobile view rather than be positioned underneath the main content. This is bad because the sidebar contains buttons the user needs to be able to click.
Looking around the app - /en/summary-document is another page using the same "sticky_sidebar" module, where the sidebar also disappears in the mobile view. However, here it's likely that's intended behaviour since the sidebar just contains subsection navigation.
The `.sticky-sidebar` CSS module is hidden by default (the mobile view), and becomes visible for tablets and above.
Stickiness aside /en/explore-your-options/summary is making use of `.sticky-sidebar__nav`, `.sticky-sidebar__heading`, `sticky-sidebar__list` …
=> Remove the stickiness of the explore-your-options/summary sidebar

app/assets/stylesheets/components/_buttons.scss, app/views/pension_summaries/summary.html.erb
This was stacking with the sidebar appointment link and since it was
titled the same it looked a bit weird.
=> Hide appointment link in mobile

app/controllers/questions_controller.rb, spec/controllers/questions_controller_spec.rb
When questions are submitted without answer we should redirect back
with the locale fragment in the URI.
=> Ensure locale is included in redirect

config/locales/cy.yml, config/locales/en.yml, content/designated_providers.cy.md, content/designated_providers.en.md
Provides the content and navigation links for Pension Wise's designated
guidance providers.
=> Designated provider content

app/controllers/tesco/bookings_controller.rb, app/models/tesco/booking.rb, app/views/tesco/bookings/_hidden_fields.html.erb, app/views/tesco/bookings/_step_3.html.erb, features/pages/tesco_booking.rb, spec/cassettes/Tesco_Api/_create/responds_successfully.yml, spec/features/tesco_booking_spec.rb, spec/lib/tesco/api_spec.rb
Ensures we now capture GDPR contact consent from Tesco customers during
their booking journey. These changes supplant the 'terms and
conditions' and 'opt out of market research' preferences.
Release should be synchronised with guidance-guarantee-programme/tesco_planner#80
=> GDPR preferences for Tesco customer journey

features/support/mock_mailgun.rb
Due to a timing issue the mailgun fake was started twice between
individual test runs this change ensures this doesn't happen.
=> Guard fake server startup

Gemfile.lock
This stops us from swallowing timeouts at the API adapter level.
=> Bump `booking_locations`

app/views/tesco/bookings/_step_3.html.erb
Gives the customer a hint that we will send an SMS reminder when they
provide a mobile phone number.
=> Add phone hint for SMS reminders

config/locales/pension_summaries.en.yml, spec/features/pension_summary_spec.rb
I spotted this typo during testing.
=> Correct a typo in the pension summary tool

Gemfile.lock, app/controllers/pension_summaries_controller.rb, app/views/pension_summaries/print.html.erb, content/pension_summary/final.cy.md, content/pension_summary/final.en.md, content/trusted_sources.cy.md, content/trusted_sources.en.md
The printed/download version will show in full while the web version
will link to the newly introduced 'Trusted sources' page. This was
deemed necessary otherwise the final pension summary step is overloaded
with the full trusted sources content.
=> Separate further signposting for web/print

app/helpers/application_helper.rb
Due to the fact we sometimes hit the limit for mailgun validation API
requests and their inability to allow us to purchase more, since the
service was provisioned via heroku - we needed a way to quickly disable
customer-facing validations if necessary.
The presence of the `DISABLE_MAILGUN_VALIDATION` environment variable
will disable customer validations. Unsetting the variable will switch
them back on.
=> Disable mailgun validations at will

app/views/booking_requests/step_two.html.erb, app/views/telephone_appointments/_step_3.html.erb
Adds the webchat link for pension type information, underneath the DC
pot question.
=> Add webchat link to booking journeys

app/views/booking_requests/completed.html.erb, features/customer_booking_request.feature
We've seen issues with confirmations and higher than usual numbers of
duplicate bookings which appear to be related. I'll disable this
confirmation while we investigate a fix.
=> Disable full confirmation for bookings temporarily

app/helpers/booking_requests_helper.rb, app/lib/booking_requests/stub_api.rb, app/views/booking_requests/completed.html.erb, features/customer_booking_request.feature, features/step_definitions/customer_booking_request_steps.rb, features/support/booking_requests.rb
Previously we were checking an incorrect predicate to determine whether the
booking was automatically fulfilled in realtime or not. Also, this was
fragile when a customer returned to the confirmation page by refresh and
the required `flash` data was no longer present. This approach ensures
bookings and appointments are displayed correctly without error.
=> Ensure appointment confirmations are displayed

app/controllers/marketing_controller.rb, app/helpers/marketing_helper.rb, app/views/marketing/index.html.erb, config/routes.rb, spec/helpers/marketing_helper_spec.rb
These are platform and campaign specific so that there's no need to use a schedule and different campaigns can run at the same time.
=> Add additional campaign landing pages

app/views/booking_requests/step_two.html.erb
This should not refer to booking requests now all locations are realtime
enabled and result in actual appointments.
=> Improve wording for submit button

app/views/booking_requests/step_two.html.erb
We don't need to ask the customer to specify unavailable times since
they're booking a realtime appointment now.
=> Improve wording for realtime

app/controllers/employer/locations_controller.rb, app/lib/employer/location.rb
Previous to the employer planner changes we had to trim the 'Tesco'
identifier from a location. We now refer to this information via the
associated 'employer' so this is no longer necessary.
=> Don't fudge a prefix for employers

app/views/employer/locations/show.html.erb
This could be misleading when a location is enabled prior to available
slots being added.
=> Improve 'unavailability' message

app/lib/telephone_appointments_api.rb
When these values are set they were not converted to integers and were
causing issues further along. This change ensures they are always
converted to integers regardless whether they're defaulted or come from
the configured environment variables.
=> Ensure configuration values are integers

app/controllers/feedbacks_controller.rb, app/views/feedbacks/_feedback_link.html.erb, config/initializers/govspeak.rb, config/locales/cy.yml, config/locales/en.yml, content/pension_type_tool.cy.md, content/pension_type_tool.en.md, content/pension_type_tool/question_1.cy.md, content/pension_type_tool/question_1.en.md, content/pension_type_tool/question_2.cy.md, content/pension_type_tool/question_2.en.md, content/pension_type_tool/question_3.cy.md, content/pension_type_tool/question_3.en.md, content/pension_type_tool/question_4.cy.md, content/pension_type_tool/question_4.en.md, spec/features/feedback_spec.rb, spec/features/questions_spec.rb
This was switched off across the board for the pension type tool since this
is a hybrid journey that uses static (therefore cached and needing cookies
stripped for cloudflare) content and cannot serve a CSRF token and the
requisite cookie. It's easier just to turn what was previously the inline
form into a link to the feedback form.
This change has been made to mitigate the anonymous pen testing the site 
has suffered recently.
=> Don't skip CSRF for feedback

app/controllers/employer/locations_controller.rb, spec/cassettes/Error_pages/employer_location_not_found.yml, spec/features/employer_booking_spec.rb, spec/features/employer_locations_spec.rb, spec/requests/error_pages_spec.rb
Previously this scenario would display the 'technical error' page. It
should instead be handled as a 404 with the associated 'missing content'
page displayed.
=> Handle missing employer locations

app/decorators/location_decorator.rb, app/views/locations/show.html.erb
Using the address components instead does not allow us to accurately
place pins when we've manually supplied geo coordinates. This can occur
when geocoding returns coordinates that do not directly correspond to
the actual, expected location when presented on a map.
=> Use geo points for map pin placement

app/decorators/location_search_result_decorator.rb, app/views/locations/search.html.erb, spec/decorators/location_search_result_decorator_spec.rb
The actual location details page was using coordinates but the search
results page was still using the encoded address to display a location
pin on a map. This change brings them up to parity.
=> Display location with coordinates in searches

Gemfile, Gemfile.lock
Bumps various frontend gems to pull in the latest changes for
accessibility and general fixes.
Pins `govuk_elements_rails` to our version that includes a fix for
missing symlinks.
=> Bump GOVUK frontend gems

app/views/employer/bookings/_step_3.html.erb, app/views/employer/bookings/confirmation.html.erb, app/views/employer/locations/index.html.erb, app/views/employer/locations/show.html.erb, spec/features/employer_booking_spec.rb
Employer appointments are facilitated via the telephone channel
temporarily due to the ongoing coronavirus crises.
=> Coronavirus changes for employer bookings

config/locales/calculators/take_cash_in_chunks.en.yml, config/locales/calculators/take_whole_pot.en.yml, content/take_cash_in_chunks.en.md, content/take_whole_pot.en.md
This was hidden under the calculate button so in some cases an
individual residing in Scotland could complete the form before noticing
it did not apply to them.
=> Make Scottish tax notice more prevalent

app/views/pension_summaries/_sidebar.html.erb
This was bleeding into the next row due to a recent change for a11y
since it was reading two buttons continually. This change addresses both
issues.
=> Address issue with sidebar spacing

app/controllers/locations_controller.rb, spec/controllers/locations_controller_spec.rb
We now need to redirect to the locations index page instead of issuing a
404 for inactive locations for 'SEO'.
=> Redirect to locations index for missing

app/controllers/smarter_signpostings_controller.rb, app/controllers/telephone_appointments_controller.rb, app/models/telephone_appointment.rb, app/views/telephone_appointments/_smarter_signposted_banner.html.erb, app/views/telephone_appointments/new.html.erb, config/routes.rb, features/pages/new_telephone_appointment.rb, features/pages/smarter_signposting_referral.rb, features/step_definitions/telephone_booking_request_steps.rb, features/telephone_booking_request.feature, spec/lib/telephone_appointments_api_spec.rb, spec/models/telephone_appointment_spec.rb
TPAS agents can book on the customer's behalf and signal a 'smarter
signposted' referral. A simple cookie is tracked through to completion
and passed along to the API when present.
=> Track smarter signposted referrals

app/views/employer/bookings/_step_3.html.erb, app/views/employer/bookings/confirmation.html.erb, app/views/employer/locations/index.html.erb, app/views/employer/locations/show.html.erb
We've hacked in some temporary wording changes to allow both
face-to-face or telephone employer appointments during the coronavirus
crisis.
=> Prep employer bookings for f2f/phone

app/models/telephone_appointment.rb, config/locales/en.yml, spec/models/telephone_appointment_spec.rb
It appears some bookings are coming through with the mobile number
autofilled into these fields. This will ensure the customer is alerted
when this happens.
=> Validate against digits in name fields

app/controllers/bsl/bsl_booking_requests_controller.rb, app/lib/bsl/mapper.rb, app/models/bsl/booking_request.rb, app/views/bsl/bsl_booking_requests/new.html.erb, config/locales/en.yml, features/pages/bsl_booking_request.rb, spec/cassettes/British_Sign_Language_bookings/Customer_places_a_BSL_booking_request_successfully.yml, spec/features/bsl_booking_spec.rb, spec/models/bsl/booking_request_spec.rb
Allows BSL customers to nominate a person for support during their
appointment and the booking process.
=> Allow customers to specify a support person

app/views/components/_cookie_banner.html.erb
These cookies are required to track first party signposting and for
opt-in data collection on the 'explore your options' journey.
=> Include necessary cookie configuration

app/controllers/telephone_appointments_controller.rb, app/lib/telephone_appointments_api.rb, app/models/telephone_appointment.rb, app/views/components/_cookie_banner.html.erb, app/views/telephone_appointments/new.html.erb, features/pages/new_telephone_appointment.rb, features/step_definitions/telephone_booking_request_steps.rb, features/telephone_booking_request.feature, spec/lib/telephone_appointments_api_spec.rb
When the customer lands on the Lloyds signposting URL they are cookied
and the flag is passed through to the bookings API upon completion. The
availability calendar is filtered also to the correct providers based on
their enrolment in the Lloyds trial.
=> Lloyds signposted appointments

app/assets/stylesheets/money-helper-overrides.scss
This was causing odd wrapping and layout of list items in particular
places. The text still appears centred to the bullet after the removal
of this rule.
=> This was causing odd layout with lists

app/controllers/pension_summaries_controller.rb, spec/features/pension_summary_spec.rb
This was not previously covered by tests and was causing a production
error to occur despite the download actually working.
=> Resolve invalid formats error

package.json
This works around heroku build issues in the staging environment.
=> Specify node version explicitly

app/assets/javascripts/application.js, app/assets/javascripts/auto-scroller.js, app/helpers/application_helper.rb, app/views/calculators/adjustable_income/_form.html.erb, app/views/calculators/guaranteed_income/_form.html.erb, app/views/calculators/leave_pot_untouched/_form.html.erb, app/views/calculators/take_cash_in_chunks/_form.html.erb, app/views/calculators/take_whole_pot/_form.html.erb, app/views/layouts/full_width_widget.html.erb, config/initializers/assets.rb, spec/javascripts/autoScrollerSpec.js, spec/javascripts/fixtures/auto-scroller-disabled.html, spec/javascripts/fixtures/auto-scroller.html
Some tools are embedded part way down on pages, which means that automatically scrolling to the top of the page on `DOMContentLoaded` is a bad idea for the user.
This PR disables this behaviour in some tools that are used in this way.
=> Disable auto scroll in some smaller tools

app/assets/stylesheets/base/_forms.scss, bower.json
Safari doesn't support rounding an outline with `border-radius`. This replaces the outline on inputs with
a shadow.
[Original ticket](https://dev.azure.com.mcas.ms/moneyandpensionsservice/Digital%20Experience%20Platform%20-%20AEM/_boards/board/t/Team%201%20(Core%20Capability)/Stories/?workitem=4254)
=> Make the outline rounded in Safari

app/assets/stylesheets/base/_forms.scss
In Safari at 320px the input element was a bit too wide, and made
things look strange.
=> Fix input overflow issue on Safari

content/pension_type_tool/defined_contribution.cy.md, content/pension_type_tool/defined_contribution.en.md, content/pension_type_tool/might_defined_contribution.cy.md, content/pension_type_tool/might_defined_contribution.en.md, content/pension_type_tool/most_cases_defined_benefit.cy.md, content/pension_type_tool/most_cases_defined_benefit.en.md, content/pension_type_tool/most_cases_defined_contribution.cy.md, content/pension_type_tool/most_cases_defined_contribution.en.md
When they're embedded in the callout markup the inline attributes are
dropped from the links. This is the most simple fix for now.
=> Ensure targets are added to links

app/helpers/application_helper.rb, app/views/nudge_appointments/_step_3.html.erb, app/views/telephone_appointments/nudge.html.erb
The IVR isn't ready for these yet so we have to temporarily switch back
to the older contact numbers until they are.
=> Revert nudge contact numbers

app/views/contact/new.html.erb
These are being rendered incorrectly due to the presence of an errant
`form-control` class.
=> Fix the display of these radio buttons

app/views/nudge_appointments/_step_3.html.erb
Some agents were incorrectly autocompleting fields and creating poorly
formed data.
=> Disable autocomplete on these fields

app/views/nudge_appointments/_step_3.html.erb
Agents have expressed some confusion about when they ought to signpost
the customer off for a third-party or other type of booking.
=> Improve right-hand panel information

app/views/telephone_appointments/_step_3.html.erb, features/pages/new_telephone_appointment.rb, spec/features/due_diligence_booking_spec.rb
When opting to change a date and time the customers would end up
out-of-channel and book a regular telephone appointment instead. This
change ensures the correct flag is sent.
=> Ensure PSG customers remain in-channel

content/pension_summary/get_an_adjustable_income.cy.md, content/pension_summary/get_an_adjustable_income.en.md, content/pension_summary/getting_help_with_debt.en.md, content/pension_summary/scams.cy.md, content/pension_summary/scams.en.md, content/pension_summary/take_cash.cy.md, content/pension_summary/take_cash.en.md, content/pension_summary/take_whole.cy.md, content/pension_summary/take_whole.en.md
These were missed during the last exercise to add them since the 'guide'
contents were not easily greppable for `a` tags.
=> Add external rel to remaining links

app/forms/booking_request_form.rb, app/models/telephone_appointment.rb, config/locales/en.yml, spec/forms/booking_request_form_spec.rb, spec/models/telephone_appointment_spec.rb
Ensures this answer is mandatory on both the phone and face-to-face customer
booking journeys.
=> Make GDPR consent mandatory

app/views/layouts/_base.html.erb, app/views/layouts/full_width_widget.html.erb, app/views/layouts/govuk_template.html.erb
This ensures all tools will embed this code when configured.
=> Move the analytics scripts to a sensible spot

config/locales/pension_summaries.cy.yml, config/locales/pension_summaries.en.yml, spec/features/pension_summary_spec.rb
This is to remove the specific mention of IPSOS, as this journey will gather user consent for research to be conducted by other trusted partners.
=> Alter research consent wording

app/views/layouts/govuk_template.html.erb
This is externally controlled to be displayed in given situations. For this particular example it's going to be initially added to the 'explore your options' journey.
=> Add informizely script for feedback

.travis.yml, app/decorators/cached_guide_decorator.rb, app/decorators/guide_decorator.rb, app/views/appointment_summaries/new.html.erb, app/views/bsl/bsl_booking_requests/new.html.erb, app/views/contact/new.html.erb, app/views/guides/show.html.erb, app/views/layouts/govuk_template.html.erb, app/views/locations/show.html.erb, app/views/pension_summaries/about_you.html.erb, app/views/pension_summaries/step_one.html.erb, app/views/telephone_appointments/new.html.erb, app/views/welsh_language/booking_requests/new.html.erb, content/adjustable_income.cy.md, content/adjustable_income.en.md, content/guaranteed_income.cy.md, content/guaranteed_income.en.md, content/leave_pot_untouched.cy.md, content/leave_pot_untouched.en.md, content/pension_type_tool/question_1.cy.md, content/pension_type_tool/question_1.en.md, content/take_cash_in_chunks.cy.md, content/take_cash_in_chunks.en.md, content/take_whole_pot.cy.md, content/take_whole_pot.en.md
This was a mixture of configuration previously and had proved ineffective in some places. We know we can and should `noindex` the whole site regardless, since the only context that content is displayed in is via Money Helper embeds.
=> Blanket `noindex` across the full site

app/views/layouts/govuk_template.html.erb
This is per a request from the data team to help differentiate the tools.
=> Rename adobe data layer event

app/domain/pension_summary.rb, lib/tasks/redact.rake, spec/factories/pension_summaries.rb, spec/models/pension_summary_spec.rb
These will be redacted two years after their initial creation.
=> Automatically redact EYO records

app/views/telephone_appointments/_step_3.html.erb
Adds a link to the pension type tool near the pot type question.
=> Signpost to pension type tool

app/controllers/pension_summaries_controller.rb, app/domain/pension_summary.rb, config/routes.rb, db/migrate/20240528161606_add_welsh_digital_to_pension_summaries.rb, db/schema.rb, spec/requests/welsh_language_explore_your_options_download_spec.rb
This allows the PW digital tool to generate a summary and download the created PDF document. The resultant summary instance is marked specifically as being created by the Welsh PWD tool to aid BI.
=> Create an endpoint for Welsh EYO

.travis.yml, app/assets/stylesheets/components/_govuk-box-highlight.scss, app/assets/stylesheets/money-helper-overrides.scss, app/controllers/application_controller.rb, app/controllers/cancels_controller.rb, app/controllers/errors_controller.rb, app/controllers/telephone_appointments_controller.rb, app/lib/telephone_appointments_api.rb, app/models/telephone_appointment.rb, app/models/telephone_cancellation.rb, app/views/cancels/failure.html.erb, app/views/cancels/new.html.erb, app/views/cancels/success.html.erb, app/views/errors/internal_server_error.html.erb, app/views/errors/not_found.html.erb, config/environments/development.rb, config/initializers/gaffe.rb, config/locales/en.yml, config/routes.rb, features/pages/telephone_appointment_cancellation.rb, features/pages/telephone_appointment_cancellation_failure.rb, features/pages/telephone_appointment_cancellation_success.rb, spec/cassettes/Telephone_appointment_cancellations/Failing_to_cancel_the_appointment.yml, spec/cassettes/Telephone_appointment_cancellations/Successfully_cancelling_the_appointment.yml, spec/features/telephone_appointment_cancellation_spec.rb, spec/features/telephone_appointment_spec.rb, spec/models/telephone_appointment_spec.rb, spec/models/telephone_cancellation_spec.rb
This journey in concert with a TAP API allows the customer to cancel an appointment by self-serve. The cancelled appointment is processed in TAP accordingly and rebooks issued after are linked to the original cancellation for reporting purposes.
=> Add customer cancellation journey

app/assets/javascripts/application.js, app/assets/javascripts/components/SelectToggle.es6, app/controllers/cancels_controller.rb, app/models/telephone_cancellation.rb, app/views/cancels/new.html.erb, spec/models/telephone_cancellation_spec.rb
Allow the customer to specify a description when they choose the 'other' option for a reason during online cancellation.
=> Add cancellation reason for 'other'

app/controllers/telephone_appointments_controller.rb
These could get stale and are no longer necessary due to improvements made to the supporting APIs.
=> Remove calendar caching for phone appointments
